/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ColumnasTablas;
import Modelo.Conexion;
import Modelo.Configuracion;
import Modelo.MySQLDAO.ConfiguracionDAO;
import Modelo.MySQLDAO.ProductoDAO;
import Modelo.MySQLDAO.ProductoPresentacionDAO;
import Modelo.Producto;
import Modelo.ProductoPresentacion;
import java.awt.event.WindowEvent;
import java.awt.event.WindowFocusListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MARCEL
 */
public class ConfigPrecioGeneral extends javax.swing.JFrame {

    DefaultTableModel modelo;
    DefaultTableModel modeloBuscarProductoPresentacion;
    Configuracion c = null;
    ProductoPresentacion pp = null;
    Producto p = null;

    public ConfigPrecioGeneral() throws SQLException, Exception {
        initComponents();
        setLocationRelativeTo(null);
        //titulos();
        cargarTablaProductos();
        
        c = new ConfiguracionDAO().Obtener(1);
        System.out.println(c);
        txtPrecioCover.setText(""+c.getPrecioGeneral());
        
        lblCodProductoCover.setText(""+c.getIdProfuctoDefecto());
        
        lblPrecioVip.setText(""+c.getPrecioVip());
        
        pp = new ProductoPresentacionDAO().Obtener(c.getIdProfuctoDefecto());
        
        p = new ProductoDAO().obtenerProducto(pp.getIdProducto());
        
        txtProductoCover.setText(p.getNombre());
        
        this.addWindowFocusListener(new WindowFocusListener() {
            @Override
            public void windowGainedFocus(WindowEvent e) {

            }

            @Override
            public void windowLostFocus(WindowEvent e) {
               dispose();
            }
        });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelProductoPresentacion = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblBuscarProductoPresentacion = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtFiltroProductoPresentacion = new javax.swing.JTextField();
        btnSeleccionarProductoPresentacion = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        btnGuardarConfCover = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblProducto = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        lblCodProductoCover = new javax.swing.JLabel();
        txtProductoCover = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPrecioCover = new javax.swing.JTextField();
        btnBuscarProducto = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblPrecioVip = new javax.swing.JLabel();

        tblBuscarProductoPresentacion = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblBuscarProductoPresentacion.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        tblBuscarProductoPresentacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBuscarProductoPresentacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBuscarProductoPresentacionMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblBuscarProductoPresentacion);

        panelProductoPresentacion.getContentPane().add(jScrollPane5, java.awt.BorderLayout.CENTER);

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 24)); // NOI18N
        jLabel10.setText("PRODUCTO");
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 140, 30));

        txtFiltroProductoPresentacion.setBackground(new java.awt.Color(204, 204, 204));
        txtFiltroProductoPresentacion.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 24)); // NOI18N
        txtFiltroProductoPresentacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFiltroProductoPresentacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroProductoPresentacionKeyReleased(evt);
            }
        });
        jPanel9.add(txtFiltroProductoPresentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 250, -1));

        panelProductoPresentacion.getContentPane().add(jPanel9, java.awt.BorderLayout.NORTH);

        btnSeleccionarProductoPresentacion.setBackground(new java.awt.Color(153, 255, 153));
        btnSeleccionarProductoPresentacion.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 24)); // NOI18N
        btnSeleccionarProductoPresentacion.setText("seleccionar");
        btnSeleccionarProductoPresentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarProductoPresentacionActionPerformed(evt);
            }
        });
        panelProductoPresentacion.getContentPane().add(btnSeleccionarProductoPresentacion, java.awt.BorderLayout.PAGE_END);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PRECIOS GENERAL");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PRECIO");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 110, -1));

        tblProductos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProductos);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 770, 230));

        btnGuardarConfCover.setBackground(new java.awt.Color(51, 255, 51));
        btnGuardarConfCover.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnGuardarConfCover.setText("GUARDAR");
        btnGuardarConfCover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarConfCoverActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardarConfCover, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, -1, 40));

        btnGuardar.setBackground(new java.awt.Color(51, 255, 51));
        btnGuardar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, -1, 50));

        btnSalir.setBackground(new java.awt.Color(255, 0, 0));
        btnSalir.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 150, 50));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("s/.");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, 30));

        lblProducto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblProducto.setForeground(new java.awt.Color(255, 255, 255));
        lblProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 770, 30));

        txtPrecio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtPrecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, 110, -1));

        lblCodProductoCover.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCodProductoCover.setForeground(new java.awt.Color(102, 102, 102));
        lblCodProductoCover.setText("...");
        jPanel2.add(lblCodProductoCover, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 110, 20));

        txtProductoCover.setEditable(false);
        txtProductoCover.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtProductoCover.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtProductoCover, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 360, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("COVER");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 30));

        txtPrecioCover.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPrecioCover.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtPrecioCover, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 110, 30));

        btnBuscarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/find.png"))); // NOI18N
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, 50, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PRODUCTO");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, 30));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PRECIOS ENTRADA GENERAL");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 770, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 50));

        lblPrecioVip.setForeground(new java.awt.Color(102, 102, 102));
        lblPrecioVip.setText("___");
        jPanel2.add(lblPrecioVip, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 110, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        int fila = tblProductos.getSelectedRow();

        lblProducto.setText(tblProductos.getValueAt(fila, 1).toString());

        txtPrecio.setText(tblProductos.getValueAt(fila, 2).toString());

        btnGuardar.setEnabled(true);
    }//GEN-LAST:event_tblProductosMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        if (!txtPrecio.getText().trim().isEmpty()) {
            try {
                int fila = tblProductos.getSelectedRow();
                int idProdPresentacion = Integer.parseInt(tblProductos.getValueAt(fila, 0).toString());
                double precio = Double.parseDouble(txtPrecio.getText());

                ProductoPresentacionDAO ppdao = new ProductoPresentacionDAO();

                if (ppdao.updatePrecioEntradaGeneral(precio, idProdPresentacion)) {
                    JOptionPane.showMessageDialog(getRootPane(), "DATOS GUARDADOS");
                    cargarTablaProductos();
                    btnGuardar.setEnabled(false);
                }
            } catch (Exception ex) {
                Logger.getLogger(ConfigPrecioGeneral.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(getRootPane(), "INDIQUE PRECIO DEL PRODUCTO SELECCIONADO");
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnGuardarConfCoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarConfCoverActionPerformed
        if (!txtPrecioCover.getText().trim().isEmpty()) {
            if (!txtProductoCover.getText().trim().isEmpty()) {                
                try {
                    double precioVIP = Double.parseDouble(lblPrecioVip.getText());
                    double precioGeneral = Double.parseDouble(txtPrecioCover.getText());
                    //dctogeneral
                    //dctofamiliar
                    int idProductoDefecto = Integer.parseInt(lblCodProductoCover.getText());
                    
                    Configuracion c = new Configuracion();
                    c.setPrecioVip(precioVIP);
                    c.setPrecioGeneral(precioGeneral);
                    c.setDctGeneral(0);
                    c.setDctoFamiliar(0);
                    c.setIdProfuctoDefecto(idProductoDefecto);
                    
                    c.setIdconfiguracion(1);
                    
                    ConfiguracionDAO cdao = new ConfiguracionDAO();
                    
                    if (cdao.Modificar(c)) {
                        JOptionPane.showMessageDialog(getRootPane(), "SE MODIFICO EL PRECIO DE ENTRADA");
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(getRootPane(), ex.getMessage());
                }
                
            } else {
                JOptionPane.showMessageDialog(getRootPane(), "INDIQUE PRODUCTO DE COVER");
            }
        } else {
            JOptionPane.showMessageDialog(getRootPane(), "INDIQUE PRECIO DE COVER");
        }
    }//GEN-LAST:event_btnGuardarConfCoverActionPerformed

    private void tblBuscarProductoPresentacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBuscarProductoPresentacionMouseClicked
        if (evt.getClickCount() == 2) {
            btnSeleccionarProductoPresentacion.doClick();
        }
    }//GEN-LAST:event_tblBuscarProductoPresentacionMouseClicked

    private void txtFiltroProductoPresentacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroProductoPresentacionKeyReleased
        try {
            LlenarTablaBuscarProductoPresentacion(txtFiltroProductoPresentacion.getText());
        } catch (Exception ex) {
            Logger.getLogger(ConfigPrecioGeneral.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtFiltroProductoPresentacionKeyReleased

    private void btnSeleccionarProductoPresentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarProductoPresentacionActionPerformed
        int fila = tblBuscarProductoPresentacion.getSelectedRow();
        try {
            if (fila >= 0) {
                txtProductoCover.setText(tblBuscarProductoPresentacion.getValueAt(fila, 1).toString());
                lblCodProductoCover.setText(tblBuscarProductoPresentacion.getValueAt(fila, 0).toString());
                panelProductoPresentacion.dispose();
            } else {
                JOptionPane.showMessageDialog(getRootPane(), "SELECCIONE UN PRODUCTO");
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnSeleccionarProductoPresentacionActionPerformed

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        panelProductoPresentacion.setBounds(300, 300, 512, 560);
        panelProductoPresentacion.setVisible(true);

        try {
            LlenarTablaBuscarProductoPresentacion("");
        } catch (Exception ex) {
            Logger.getLogger(ConfigPrecioGeneral.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigPrecioGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigPrecioGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigPrecioGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigPrecioGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    try {
                        new ConfigPrecioGeneral().setVisible(true);
                    } catch (Exception ex) {
                        Logger.getLogger(ConfigPrecioGeneral.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (Exception ex) {
                    Logger.getLogger(ConfigPrecioGeneral.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarConfCover;
    private javax.swing.JButton btnSalir;
    public javax.swing.JButton btnSeleccionarProductoPresentacion;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblCodProductoCover;
    private javax.swing.JLabel lblPrecioVip;
    private javax.swing.JLabel lblProducto;
    public javax.swing.JDialog panelProductoPresentacion;
    public javax.swing.JTable tblBuscarProductoPresentacion;
    private javax.swing.JTable tblProductos;
    public javax.swing.JTextField txtFiltroProductoPresentacion;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPrecioCover;
    private javax.swing.JTextField txtProductoCover;
    // End of variables declaration//GEN-END:variables

    private void titulos() {
        String titulos[] = {"COD", "PRODUCTO", "PRECIO"};
        modelo = new DefaultTableModel(null, titulos);
        tblProductos.setModel(modelo);
    }

    private void cargarTablaProductos() throws SQLException {
        titulos();
        LimpiarTabla(tblProductos, modelo);
        Conexion con = new Conexion();
        try {
            con.conectar();
            String sql = "SELECT productopresentacion.idproductopresentacion, producto.nombre, productopresentacion.precio3\n"
                    + "FROM productopresentacion\n"
                    + "inner join producto on productopresentacion.idproducto = producto.idproducto\n"
                    + "where stock3 = 1 and idalmacen = 2";

            PreparedStatement pst = con.getConexion().prepareStatement(sql);
            ResultSet res = pst.executeQuery();

            Object datos[] = new Object[3];

            while (res.next()) {
                datos[0] = res.getInt(1);
                datos[1] = res.getString(2);
                datos[2] = res.getDouble(3);
                modelo.addRow(datos);
            }

            tblProductos.setModel(modelo);
            pst.close();
            res.close();

            new ColumnasTablas().tresColumnas(tblProductos, 50, 500, 100);

        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            con.cerrar();
        }
    }

    public void LlenarTablaBuscarProductoPresentacion(String nomProd) throws Exception {
        titulosBuscarComponentes();
        LimpiarTabla(tblBuscarProductoPresentacion, modeloBuscarProductoPresentacion);
        Conexion con = new Conexion();
        try {
            con.conectar();
            String sql = "select pp.idproductopresentacion, p.nombre, pre.descripcion from producto p\n"
                    + "INNER JOIN productopresentacion pp on p.idproducto = pp.idproducto\n"
                    + "INNER JOIN presentacion pre on pp.idpresentacion = pre.idpresentacion\n"
                    + "WHERE pp.idalmacen = 2 AND p.nombre like '%" + nomProd + "%'";

            Object[] datos = new Object[3];
            PreparedStatement pst = con.getConexion().prepareStatement(sql);
            ResultSet res = pst.executeQuery();

            while (res.next()) {
                datos[0] = res.getInt(1);
                datos[1] = res.getString(2);
                datos[2] = res.getString(3);

                modeloBuscarProductoPresentacion.addRow(datos);
            }

            tblBuscarProductoPresentacion.setModel(modeloBuscarProductoPresentacion);
            new ColumnasTablas().tresColumnas(tblBuscarProductoPresentacion, 50, 200, 100);

            pst.close();
            res.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            con.cerrar();
        }
    }

    public void titulosBuscarComponentes() {
        String titulos[] = {"ID", "PRODUCTO", "PRESENTACION"};
        modeloBuscarProductoPresentacion = new DefaultTableModel(null, titulos);
        tblBuscarProductoPresentacion.setModel(modeloBuscarProductoPresentacion);
    }

    private void LimpiarTabla(JTable tabla, DefaultTableModel model) {
        for (int i = 0; i < tabla.getRowCount(); i++) {
            model.removeRow(i);
            i -= 1;
        }
    }

}
