package Vista;

import Controlador.AbrirCajaControl;
import Controlador.ColumnasTablas;
import Controlador.Cronometro;
import Controlador.ManejadorFechas;
import Controlador.MyiReportVisor;
import Controlador.ProductoControl;
import Modelo.Conexion;
import Modelo.EntradaVip;
import Modelo.MySQLDAO.CajaDAO;
import Modelo.MySQLDAO.ConfiguracionDAO;
import Modelo.MySQLDAO.EntradaVipDAO;
import Modelo.MySQLDAO.FlujoCajaDAO;
import Modelo.MySQLDAO.UsuarioDAO;

import Modelo.Venta;
import Modelo.MySQLDAO.VentaDAO;
import Modelo.VentaEntrada;
import Modelo.MySQLDAO.VentaEntradaDAO;
import Modelo.MySQLDAO.VentaEntradaVipDAO;
import Modelo.VentaEntradaVip;
import java.awt.event.WindowEvent;
import java.awt.event.WindowFocusListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Grover
 */
public class EntradaVipBox extends javax.swing.JFrame {

    DefaultTableModel modelo = null;
    MyiReportVisor mrv;
    HashMap parametros = new HashMap();
    double costoVIP;
    int producto = 0;

    public EntradaVipBox(String usuario) throws Exception {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
        txtUsuario.setText(usuario);
        txtFecha.setText(new ManejadorFechas().getFechaActual());
        new Cronometro().iniciarCronometro(txtHora);
        txtCaja.setText(new AbrirCajaControl().getCajaDeUsuario(usuario));
        costoVIP = new ConfiguracionDAO().getPrecios(2);
        LlenarTabla();
        
        
    }

    public EntradaVipBox() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotones = new javax.swing.ButtonGroup();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtCaja = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnCobrar = new javax.swing.JButton();
        txtTotalCobrar = new javax.swing.JTextField();
        lblProducto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNumPersonas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBox = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ENTRADAS VIP - BOX");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(0, 102, 153));
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("ENTRADAS");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 30));

        jLabel15.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("VIP - BOX");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, 30));

        jLabel18.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel18.setText("VIP - BOX");
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 20, -1, 30));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/billete.png"))); // NOI18N
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 70));

        txtFecha.setEditable(false);
        txtFecha.setBackground(new java.awt.Color(0, 102, 153));
        txtFecha.setForeground(new java.awt.Color(255, 255, 255));
        txtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFecha.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "FECHA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1730, 20, 90, -1));

        txtHora.setEditable(false);
        txtHora.setBackground(new java.awt.Color(0, 102, 153));
        txtHora.setForeground(new java.awt.Color(255, 255, 255));
        txtHora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHora.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "HORA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(1640, 20, 90, -1));

        txtUsuario.setEditable(false);
        txtUsuario.setBackground(new java.awt.Color(0, 102, 153));
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "USUARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 20, 140, -1));

        jLabel17.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel17.setText("ENTRADAS");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 20, -1, 30));

        txtCaja.setEditable(false);
        txtCaja.setBackground(new java.awt.Color(0, 102, 153));
        txtCaja.setForeground(new java.awt.Color(255, 255, 255));
        txtCaja.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCaja.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "CAJA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.add(txtCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 140, -1));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 70));

        jPanel6.setBackground(new java.awt.Color(0, 102, 153));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 0, 0));
        jLabel19.setText("DISCOTECK");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, -1, -1));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel12.setText("DISCOTECK");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(942, 0, -1, -1));

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("MISTER JUERGA");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, -1, -1));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel11.setText("MISTER JUERGA");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 0, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1010, 1920, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn7.setBackground(new java.awt.Color(0, 153, 0));
        btn7.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn7.setForeground(new java.awt.Color(255, 255, 255));
        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iphone_7.png"))); // NOI18N
        btn7.setContentAreaFilled(false);
        btn7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn7.setFocusPainted(false);
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel2.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 210, 180));

        btn8.setBackground(new java.awt.Color(0, 153, 0));
        btn8.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn8.setForeground(new java.awt.Color(255, 255, 255));
        btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iphone_8.png"))); // NOI18N
        btn8.setContentAreaFilled(false);
        btn8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn8.setFocusPainted(false);
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel2.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 210, 180));

        btn9.setBackground(new java.awt.Color(0, 153, 0));
        btn9.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn9.setForeground(new java.awt.Color(255, 255, 255));
        btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iphone_9.png"))); // NOI18N
        btn9.setContentAreaFilled(false);
        btn9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn9.setFocusPainted(false);
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 210, 180));

        btn4.setBackground(new java.awt.Color(0, 153, 0));
        btn4.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iphone_4.png"))); // NOI18N
        btn4.setContentAreaFilled(false);
        btn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn4.setFocusPainted(false);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 210, 180));

        btn5.setBackground(new java.awt.Color(0, 153, 0));
        btn5.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 255, 255));
        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iphone_5.png"))); // NOI18N
        btn5.setContentAreaFilled(false);
        btn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn5.setFocusPainted(false);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel2.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 210, 180));

        btn6.setBackground(new java.awt.Color(0, 153, 0));
        btn6.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iphone_6.png"))); // NOI18N
        btn6.setContentAreaFilled(false);
        btn6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn6.setFocusPainted(false);
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel2.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 210, 180));

        btn1.setBackground(new java.awt.Color(0, 153, 0));
        btn1.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iphone_1.png"))); // NOI18N
        btn1.setContentAreaFilled(false);
        btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn1.setFocusPainted(false);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 210, 180));

        btn2.setBackground(new java.awt.Color(0, 153, 0));
        btn2.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iphone_2.png"))); // NOI18N
        btn2.setContentAreaFilled(false);
        btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn2.setFocusPainted(false);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 210, 180));

        btn3.setBackground(new java.awt.Color(0, 153, 0));
        btn3.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iphone_3.png"))); // NOI18N
        btn3.setContentAreaFilled(false);
        btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn3.setFocusPainted(false);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 210, 180));

        btn0.setBackground(new java.awt.Color(0, 153, 0));
        btn0.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn0.setForeground(new java.awt.Color(255, 255, 255));
        btn0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iphone_0.png"))); // NOI18N
        btn0.setContentAreaFilled(false);
        btn0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn0.setFocusPainted(false);
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel2.add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 650, 210, 180));

        btnDel.setBackground(new java.awt.Color(255, 0, 0));
        btnDel.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btnDel.setForeground(new java.awt.Color(255, 255, 255));
        btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/borrar.png"))); // NOI18N
        btnDel.setContentAreaFilled(false);
        btnDel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDel.setFocusPainted(false);
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        jPanel2.add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 210, 180));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 710, 940));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCobrar.setBackground(new java.awt.Color(0, 153, 0));
        btnCobrar.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        btnCobrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCobrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cobrar.png"))); // NOI18N
        btnCobrar.setText("COBRAR");
        btnCobrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 820, 730, 110));

        txtTotalCobrar.setEditable(false);
        txtTotalCobrar.setBackground(new java.awt.Color(51, 51, 51));
        txtTotalCobrar.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        txtTotalCobrar.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalCobrar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalCobrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        txtTotalCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalCobrarActionPerformed(evt);
            }
        });
        jPanel3.add(txtTotalCobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 660, 730, 140));

        lblProducto.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lblProducto.setForeground(new java.awt.Color(255, 255, 255));
        lblProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProducto.setText("PRODUCTO...");
        jPanel3.add(lblProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, 730, 50));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("S/.");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 620, -1, -1));

        txtNumPersonas.setEditable(false);
        txtNumPersonas.setBackground(new java.awt.Color(51, 51, 51));
        txtNumPersonas.setFont(new java.awt.Font("Consolas", 1, 60)); // NOI18N
        txtNumPersonas.setForeground(new java.awt.Color(255, 255, 255));
        txtNumPersonas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumPersonasActionPerformed(evt);
            }
        });
        jPanel3.add(txtNumPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 250, 150));

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CANTIDAD");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 250, 30));

        jLabel14.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("TOTAL");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 620, -1, -1));

        tblBox.setBackground(new java.awt.Color(153, 153, 255));
        tblBox.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 25)); // NOI18N
        tblBox.setForeground(new java.awt.Color(255, 255, 255));
        tblBox.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBox.setDragEnabled(true);
        tblBox.setFocusable(false);
        tblBox.setRowHeight(26);
        tblBox.setRowMargin(2);
        tblBox.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblBox.getTableHeader().setResizingAllowed(false);
        tblBox.getTableHeader().setReorderingAllowed(false);
        tblBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBoxMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBox);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 840, 530));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 1210, 940));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        String captura = txtNumPersonas.getText() + 7;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
        //txtCovers.setText("" + new ProductoControl().covers(2, numPersonas));
        //txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
        //int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
        lblProducto.setText("ENTRADA VIP");
        txtTotalCobrar.setText("" + new ProductoControl().total(cantPersonas, costoVIP));
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        String captura = txtNumPersonas.getText() + 8;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
        //txtCovers.setText("" + new ProductoControl().covers(2, numPersonas));
        //txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
        //int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
        lblProducto.setText("ENTRADA VIP");
        txtTotalCobrar.setText("" + new ProductoControl().total(cantPersonas, costoVIP));
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        String captura = txtNumPersonas.getText() + 9;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
//        txtCovers.setText("" + new ProductoControl().covers(2, numPersonas));
//        txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
//        int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
        lblProducto.setText("ENTRADA VIP");
        txtTotalCobrar.setText("" + new ProductoControl().total(cantPersonas, costoVIP));
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        String captura = txtNumPersonas.getText() + 4;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
//        txtCovers.setText("" + new ProductoControl().covers(2, numPersonas));
//        txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
//        int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
        lblProducto.setText("ENTRADA VIP");
        txtTotalCobrar.setText("" + new ProductoControl().total(cantPersonas, costoVIP));
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        String captura = txtNumPersonas.getText() + 5;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
//        txtCovers.setText("" + new ProductoControl().covers(2, numPersonas));
//        txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
//        int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
        lblProducto.setText("ENTRADA VIP");
        txtTotalCobrar.setText("" + new ProductoControl().total(cantPersonas, costoVIP));
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        String captura = txtNumPersonas.getText() + 6;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
//        txtCovers.setText("" + new ProductoControl().covers(2, numPersonas));
//        txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
//        int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
        lblProducto.setText("ENTRADA VIP");
        txtTotalCobrar.setText("" + new ProductoControl().total(cantPersonas, costoVIP));
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        String captura = txtNumPersonas.getText() + 1;
        txtNumPersonas.setText(captura);
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
        lblProducto.setText("ENTRADA VIP");
        txtTotalCobrar.setText("" + new ProductoControl().total(cantPersonas, costoVIP));

    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        String captura = txtNumPersonas.getText() + 2;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
//        txtCovers.setText("" + new ProductoControl().covers(2, numPersonas));
//        txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
//        int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
        lblProducto.setText("ENTRADA VIP");
        txtTotalCobrar.setText("" + new ProductoControl().total(cantPersonas, costoVIP));
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        String captura = txtNumPersonas.getText() + 3;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
//        txtCovers.setText("" + new ProductoControl().covers(2, numPersonas));
//        txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
//        int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
        lblProducto.setText("ENTRADA VIP");
        txtTotalCobrar.setText("" + new ProductoControl().total(cantPersonas, costoVIP));
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        String captura = txtNumPersonas.getText() + 0;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
//        txtCovers.setText("" + new ProductoControl().covers(2, numPersonas));
//        txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
//        int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
        lblProducto.setText("ENTRADA VIP");
        txtTotalCobrar.setText("" + new ProductoControl().total(cantPersonas, costoVIP));

    }//GEN-LAST:event_btn0ActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed

        txtNumPersonas.setText("");
//        txtCovers.setText("");
        txtTotalCobrar.setText("");
        lblProducto.setText("ENTRADA VIP");
        tblBox.clearSelection();
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarActionPerformed
        try {
            if (!txtNumPersonas.getText().trim().isEmpty()) {
                int fila = tblBox.getSelectedRow();
                if (fila >= 0) {

                    //REGISTRAR LA VENTA
                    EntradaVip v = new EntradaVip();
                    v.setFecha(new ManejadorFechas().getFechaActualMySQL());
                    v.setHora(new ManejadorFechas().getHoraActual());
                    v.setIdUsuario(new UsuarioDAO().getIdUsuario(txtUsuario.getText()));
                    v.setIdCliente(1);
                    v.setIdTipoComprobante(1);
                    v.setEstado(1);
                    v.setTipopago(1);
                    v.setnOperacion("0");
                    v.setIdCaja(2);
                    System.out.println(v.getIdCaja());
                    v.setIdFlujoCaja(new FlujoCajaDAO().getIdFlujo(new UsuarioDAO().getIdUsuario(txtUsuario.getText()), new CajaDAO().getIdCaja(txtCaja.getText())));
                    System.out.println(new FlujoCajaDAO().getIdFlujo(new UsuarioDAO().getIdUsuario(txtUsuario.getText()), new CajaDAO().getIdCaja(txtCaja.getText())));
                    //v.setIdFlujoCaja(2);

                    EntradaVipDAO vdao = new EntradaVipDAO();
                    if (vdao.Registrar(v)) {
                        System.out.println("Entrada VIP registrada");
                    }
                    //segundo se registra las entradas

                    VentaEntradaVip ve = new VentaEntradaVip();
                    int idEntrada = new EntradaVipDAO().getIdUltimaEntradaVip();
                    System.out.println("Ultima entrada vip! " + idEntrada);
                    ve.setNumPersonas(Integer.parseInt(txtNumPersonas.getText()));
                    ve.setNumCovers(Integer.parseInt(txtNumPersonas.getText()));
                    ve.setTotal(Double.parseDouble(txtTotalCobrar.getText()));
                    if (producto != 0) {
                        ve.setTipoEntrada("BOX");
                    } else {
                        ve.setTipoEntrada("ENTRADA VIP");
                    }

                    ve.setIdEntradaVip(idEntrada);
                    ve.setIdProd(producto);

                    VentaEntradaVipDAO vedao = new VentaEntradaVipDAO();
                    if (vedao.Registrar(ve)) {
                        System.out.println("ingreso al if");
//                JOptionPane.showMessageDialog(rootPane, "VENTA REGISTRADA");
                        if (producto != 0) {
                            parametros.put("producto", lblProducto.getText());
                            parametros.put("personas", Integer.parseInt(txtNumPersonas.getText()));
                            parametros.put("total", Double.parseDouble(txtTotalCobrar.getText()));
                            parametros.put("nom_cajero", txtUsuario.getText());
                            parametros.put("idventa", idEntrada);
                            mrv = new MyiReportVisor(System.getProperty("user.dir") + "\\reportes\\BoletaEntradaBOX.jrxml", parametros, getPageSize());
                            mrv.setNombreArchivo("BoletaBOX");
                            mrv.exportarADocxConCopia("boletabox.docx");
                        } else {
                            parametros.put("nom_cajero", txtUsuario.getText());
                            parametros.put("idventa", idEntrada);
                            mrv = new MyiReportVisor(System.getProperty("user.dir") + "\\reportes\\BoletaEntradaVip.jrxml", parametros, getPageSize());
                            mrv.setNombreArchivo("BoletaVIP");
                            mrv.exportarADocxConCopia("Boletavip.docx");
                        }
                        btnDel.doClick();
                    }
                } else {
                    JOptionPane.showMessageDialog(getRootPane(), "SELECCIONE UN PRODUCTO DE LA LISTA");
                }
            } else {
                JOptionPane.showMessageDialog(getRootPane(), "INGRESE CANTIDAD");
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnCobrarActionPerformed

    private void txtNumPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumPersonasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumPersonasActionPerformed

    private void txtTotalCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalCobrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalCobrarActionPerformed

    private void tblBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBoxMouseClicked

        if (!txtNumPersonas.getText().trim().isEmpty()) {
            int fila = tblBox.getSelectedRow();
            producto = Integer.parseInt(tblBox.getValueAt(fila, 0).toString());
            double cantidad = Double.parseDouble(txtNumPersonas.getText());
            lblProducto.setText(tblBox.getValueAt(fila, 1).toString());
            txtTotalCobrar.setText("" + (cantidad * Double.parseDouble(tblBox.getValueAt(fila, 2).toString())));
        } else {
            JOptionPane.showMessageDialog(getRootPane(), "INDIQUE CANTIDAD");
            tblBox.clearSelection();
        }

    }//GEN-LAST:event_tblBoxMouseClicked
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntradaVipBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnCobrar;
    private javax.swing.JButton btnDel;
    private javax.swing.ButtonGroup grupoBotones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblProducto;
    public javax.swing.JTable tblBox;
    private javax.swing.JTextField txtCaja;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtNumPersonas;
    private javax.swing.JTextField txtTotalCobrar;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void titulos() {
        String titulos[] = {"COD", "PRODUCTO", "PRECIO", "STOCK"};
        modelo = new DefaultTableModel(null, titulos);
        tblBox.setModel(modelo);
    }

    private void LlenarTabla() throws Exception {
        titulos();
        LimpiarTabla(tblBox, modelo);
        Conexion con = new Conexion();
        try {
            con.conectar();
            String sql = "SELECT prodpromocion.idproductopresentacion, producto.nombre, prodpromocion.precio1, productopresentacion.stock2\n"
                    + "FROM prodpromocion\n"
                    + "inner join productopresentacion on prodpromocion.idproductopresentacion = productopresentacion.idproductopresentacion\n"
                    + "inner join producto on productopresentacion.idproducto = producto.idproducto";
            PreparedStatement pst = con.getConexion().prepareStatement(sql);

            ResultSet res = pst.executeQuery();

            Object datos[] = new Object[4];

            while (res.next()) {
                datos[0] = res.getInt(1);
                datos[1] = res.getString(2);
                //crear condicional de la hora para modificar el precio(precio1->precio2) despues de las 12:00 de la noche            
                datos[2] = res.getDouble(3);
                datos[3] = res.getDouble(4);

                modelo.addRow(datos);
            }

            tblBox.setModel(modelo);

            pst.close();
            res.close();

            new ColumnasTablas().cuatroColumnas(tblBox, 50, 500, 100, 100);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            con.cerrar();
        }

    }

    private void LimpiarTabla(JTable tabla, DefaultTableModel model) {
        for (int i = 0; i < tabla.getRowCount(); i++) {
            model.removeRow(i);
            i -= 1;
        }
    }

    private int getPageSize() {
        int filas = 1;
        System.out.println("cantidad de filas: " + filas);
        int rowCount = 1;//FILAS DE GRACIA
        int fontSize = 7;//TAMAÑO DE LETRA DEL DETAIL
        int rowSize = fontSize + 2;//TAMAÑO DE LA FILA
        int caracteresPorLinea = 16;// CANTIDAD DE CARACTERES PARA QUE PASE A LA SIGTE LINEA
        for (int i = 0; i < filas; i++) {
            //String descripcionDeProducto = tbl_venta.getValueAt(i, 1).toString();
            rowCount += 1;//(1 + (int) (descripcionDeProducto.length() / caracteresPorLinea));
        }
        int cabecera = 175;
        int piePagina = 85;
//        int pageSize = (rowCount * rowSize) + cabecera + piePagina;
        int pageSize = (rowCount) + cabecera + piePagina;
        System.out.println("Cantidad de Filas finale:" + rowCount);
        System.out.println("pageSize:" + pageSize);
        return pageSize;
    }

}
