package Vista;

import Controlador.AbrirCajaControl;
import Controlador.ColumnasTablas;
import Controlador.Cronometro;
import Controlador.ManejadorFechas;
import Controlador.MyiReportVisor;
import Controlador.StockBebidasPreparadas;
import Modelo.Conexion;
import Modelo.Configuracion;
import Modelo.MySQLDAO.CajaDAO;
import Modelo.MySQLDAO.ConfiguracionDAO;
import Modelo.MySQLDAO.EntradaGeneralDAO;
import Modelo.MySQLDAO.FlujoCajaDAO;
import Modelo.MySQLDAO.UsuarioDAO;
import Modelo.EntradaGeneral;
import Modelo.MySQLDAO.ProductoDAO;
import Modelo.MySQLDAO.ProductoPresentacionDAO;
import Modelo.MySQLDAO.VentaEntradaDAO;
import Modelo.Producto;
import Modelo.ProductoPresentacion;
import Modelo.VentaEntrada;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class EntradaGeneralVista extends javax.swing.JFrame {

    MyiReportVisor mrv;
    HashMap parametros = new HashMap();
    DefaultTableModel modelo;

    double costoGeneral;
    boolean seleccionado = true;
    Configuracion c = null;
    ProductoPresentacion pp = null;
    Producto p = null;
    int producto = 0;
    String prodGeneral = "COVER";

    public EntradaGeneralVista(String usuario) throws Exception {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
        this.setBackground(Color.WHITE);
        titulos();
        cargarTablaProductos();
        txtUsuario.setText(usuario);
        txtFecha.setText(new ManejadorFechas().getFechaActual());
        c = new ConfiguracionDAO().Obtener(1);
        lblPrecioCover.setText("" + c.getPrecioGeneral());
        pp = new ProductoPresentacionDAO().Obtener(c.getIdProfuctoDefecto());
        p = new ProductoDAO().obtenerProducto(pp.getIdProducto());
        lblProductoCover.setText("" + p.getNombre());
        new Cronometro().iniciarCronometro(txtHora);
        txtCaja.setText(new AbrirCajaControl().getCajaDeUsuario(usuario));

        producto = c.getIdProfuctoDefecto();
    }

    public EntradaGeneralVista() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonesOpcion = new javax.swing.ButtonGroup();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtCaja = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblCodProductoCover = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblProductoCover = new javax.swing.JLabel();
        lblPrecioCover = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnCobrar = new javax.swing.JButton();
        txtTotalCobrar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblProducto = new javax.swing.JLabel();
        txtNumPersonas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ENTRADAS");
        setBounds(new java.awt.Rectangle(0, 0, 1000, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(0, 102, 102));
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("ENTRADAS");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 30));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/billete.png"))); // NOI18N
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 70));

        txtFecha.setEditable(false);
        txtFecha.setBackground(new java.awt.Color(0, 102, 102));
        txtFecha.setForeground(new java.awt.Color(255, 255, 255));
        txtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFecha.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "FECHA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 10, 90, -1));

        txtHora.setEditable(false);
        txtHora.setBackground(new java.awt.Color(0, 102, 102));
        txtHora.setForeground(new java.awt.Color(255, 255, 255));
        txtHora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHora.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "HORA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 10, 90, -1));

        txtUsuario.setEditable(false);
        txtUsuario.setBackground(new java.awt.Color(0, 102, 102));
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "USUARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 10, 140, -1));

        jLabel17.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel17.setText("ENTRADAS");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 20, -1, 30));

        txtCaja.setEditable(false);
        txtCaja.setBackground(new java.awt.Color(0, 102, 102));
        txtCaja.setForeground(new java.awt.Color(255, 255, 255));
        txtCaja.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCaja.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "CAJA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.add(txtCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 140, -1));

        jLabel16.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("GENERAL");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 20, -1, 30));

        jLabel18.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel18.setText("GENERAL");
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, 30));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 70));

        jPanel6.setBackground(new java.awt.Color(60, 60, 60));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 0, 0));
        jLabel19.setText("DISCOTECK");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(932, 0, -1, -1));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel12.setText("DISCOTECK");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, -1, -1));

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("MISTER JUERGA");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, -1, -1));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel11.setText("MISTER JUERGA");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 0, -1, -1));

        lblCodProductoCover.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCodProductoCover.setForeground(new java.awt.Color(204, 204, 255));
        lblCodProductoCover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCodProductoCover.setText(".......");
        jPanel6.add(lblCodProductoCover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 30));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1020, 1920, 40));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn7.setBackground(new java.awt.Color(0, 153, 0));
        btn7.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn7.setForeground(new java.awt.Color(255, 255, 255));
        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/siete_in.png"))); // NOI18N
        btn7.setContentAreaFilled(false);
        btn7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn7.setFocusPainted(false);
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel2.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 210, 180));

        btn8.setBackground(new java.awt.Color(0, 153, 0));
        btn8.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn8.setForeground(new java.awt.Color(255, 255, 255));
        btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ocho_in.png"))); // NOI18N
        btn8.setContentAreaFilled(false);
        btn8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn8.setFocusPainted(false);
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel2.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 210, 180));

        btn4.setBackground(new java.awt.Color(0, 153, 0));
        btn4.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuatro_in.png"))); // NOI18N
        btn4.setContentAreaFilled(false);
        btn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn4.setFocusPainted(false);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 210, 180));

        btn5.setBackground(new java.awt.Color(0, 153, 0));
        btn5.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 255, 255));
        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cinco_in.png"))); // NOI18N
        btn5.setContentAreaFilled(false);
        btn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn5.setFocusPainted(false);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel2.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 210, 180));

        btn6.setBackground(new java.awt.Color(0, 153, 0));
        btn6.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seis_in.png"))); // NOI18N
        btn6.setContentAreaFilled(false);
        btn6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn6.setFocusPainted(false);
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel2.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 210, 180));

        btn2.setBackground(new java.awt.Color(0, 153, 0));
        btn2.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dos_in.png"))); // NOI18N
        btn2.setContentAreaFilled(false);
        btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn2.setFocusPainted(false);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 210, 180));

        btn3.setBackground(new java.awt.Color(0, 153, 0));
        btn3.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tres_in.png"))); // NOI18N
        btn3.setContentAreaFilled(false);
        btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn3.setFocusPainted(false);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 210, 180));

        btn0.setBackground(new java.awt.Color(0, 153, 0));
        btn0.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn0.setForeground(new java.awt.Color(255, 255, 255));
        btn0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cero_in.png"))); // NOI18N
        btn0.setContentAreaFilled(false);
        btn0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn0.setFocusPainted(false);
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel2.add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 600, 210, 180));

        btnDel.setBackground(new java.awt.Color(255, 255, 255));
        btnDel.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btnDel.setForeground(new java.awt.Color(255, 255, 255));
        btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/borrar.png"))); // NOI18N
        btnDel.setContentAreaFilled(false);
        btnDel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDel.setFocusPainted(false);
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        jPanel2.add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 210, 180));

        btn1.setBackground(new java.awt.Color(0, 153, 0));
        btn1.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/uno_in.png"))); // NOI18N
        btn1.setContentAreaFilled(false);
        btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn1.setFocusPainted(false);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 210, 180));

        btn9.setBackground(new java.awt.Color(0, 153, 0));
        btn9.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn9.setForeground(new java.awt.Color(255, 255, 255));
        btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nueve_in.png"))); // NOI18N
        btn9.setContentAreaFilled(false);
        btn9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn9.setFocusPainted(false);
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 210, 180));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProductoCover.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblProductoCover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProductoCover.setText(".......");
        jPanel1.add(lblProductoCover, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 300, 30));

        lblPrecioCover.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblPrecioCover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrecioCover.setText(".......");
        jPanel1.add(lblPrecioCover, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 300, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("PRECIO COVER / ENTRADA:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("PRODUCTO:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 810, 670, 110));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 720, 950));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCobrar.setBackground(new java.awt.Color(0, 153, 0));
        btnCobrar.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        btnCobrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCobrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cobrar.png"))); // NOI18N
        btnCobrar.setText("COBRAR");
        btnCobrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 820, 710, 110));

        txtTotalCobrar.setEditable(false);
        txtTotalCobrar.setBackground(new java.awt.Color(0, 102, 102));
        txtTotalCobrar.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        txtTotalCobrar.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalCobrar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalCobrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        txtTotalCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalCobrarActionPerformed(evt);
            }
        });
        jPanel3.add(txtTotalCobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 680, 450, 130));

        jLabel13.setFont(new java.awt.Font("Consolas", 1, 60)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("TOTAL");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 680, 190, 130));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("S/.");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 680, -1, -1));

        lblProducto.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lblProducto.setForeground(new java.awt.Color(255, 255, 255));
        lblProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel3.add(lblProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 610, 710, 50));

        txtNumPersonas.setEditable(false);
        txtNumPersonas.setBackground(new java.awt.Color(0, 102, 102));
        txtNumPersonas.setFont(new java.awt.Font("Consolas", 0, 60)); // NOI18N
        txtNumPersonas.setForeground(new java.awt.Color(255, 255, 255));
        txtNumPersonas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(txtNumPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 710, 110));

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CANTIDAD");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 120, 20));

        tblProductos.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProductos.setRowHeight(40);
        tblProductos.setRowMargin(2);
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductos);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 970, 430));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, 1200, 950));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        String captura = txtNumPersonas.getText() + 3;
        txtNumPersonas.setText(captura);
        lblProducto.setText(prodGeneral);
        txtTotalCobrar.setText("" + c.getPrecioGeneral() * Double.parseDouble(txtNumPersonas.getText()));
    }//GEN-LAST:event_btn3ActionPerformed

    private void btnCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarActionPerformed
        try {
            //REGISTRAR LA VENTA
            EntradaGeneral v = new EntradaGeneral();
            v.setFecha(new ManejadorFechas().getFechaActualMySQL());
            v.setHora(new ManejadorFechas().getHoraActual());
            v.setIdUsuario(new UsuarioDAO().getIdUsuario(txtUsuario.getText()));
            v.setIdCliente(1);
            v.setIdTipoComprobante(1);
            v.setEstado(1);
            v.setTipopago(1);
            v.setnOperacion("0");
            v.setIdCaja(1);
            System.out.println(v.getIdCaja());
            v.setIdFlujoCaja(new FlujoCajaDAO().getIdFlujo(new UsuarioDAO().getIdUsuario(txtUsuario.getText()), new CajaDAO().getIdCaja(txtCaja.getText())));
            //v.setIdFlujoCaja(1);

            EntradaGeneralDAO vdao = new EntradaGeneralDAO();
            if (vdao.Registrar(v)) {
                System.out.println("Entrada general registrada");
            }
            //segundo se registra las ENTRADAS

            int idVenta = new EntradaGeneralDAO().getIdDeUltimaEntradaGeneralRegistrada();/////////////////////////////
            System.out.println("ultima entrada: " + idVenta);

            VentaEntrada ve = new VentaEntrada();
            ve.setNumPersonas(Integer.parseInt(txtNumPersonas.getText()));
            ve.setNumCovers(Integer.parseInt(txtNumPersonas.getText()));
            ve.setTotal(Double.parseDouble(txtTotalCobrar.getText()));
            ve.setTipoEntrada("ENTRADA GENERAL");
            ve.setIdVenta(idVenta);
            ve.setIdProd(producto);
            //la fecha es automatica

            VentaEntradaDAO vedao = new VentaEntradaDAO();
            if (vedao.registrar(ve)) {
                //restar Stock
                restarStock(ve.getNumCovers());

                parametros.put("nom_cajero", txtUsuario.getText());
                parametros.put("id_venta", idVenta);
                mrv = new MyiReportVisor(System.getProperty("user.dir") + "\\reportes\\boleta.jrxml", parametros, getPageSize());
                mrv.setNombreArchivo("BoletaEntrada");

                mrv.exportarADocxConCopia("boletas.docx");

                HashMap par2 = new HashMap();
                System.out.println("Imprimiendo Cover");
                par2.put("nroComprobante", idVenta);
                String flagCover = lblProducto.getText();
                par2.put("nombreCover", flagCover);
                MyiReportVisor mrv2 = new MyiReportVisor(System.getProperty("user.dir") + "\\reportes\\coversNormalT1.jrxml", par2, getPageSize(1, 28, 40, 50));
                mrv2.setNombreArchivo("Cover Cerveza");
                int numerodeCopias = ve.getNumCovers();
                for (int i = 1; i <= numerodeCopias; i++) {
                    pp = new ProductoPresentacionDAO().Obtener(producto);
                    System.out.println("EL ID DE PROD A ANALIZAR ES: " + pp.getIdProducto());
                    StockBebidasPreparadas sbp = new StockBebidasPreparadas(pp.getIdProducto(), 2);
                    sbp.updateStockVenta();
                    mrv2.exportarADocxConCopia("covers" + i + ".docx");
                }
                txtNumPersonas.setText("");
                txtTotalCobrar.setText("");
                lblProducto.setText("");
                tblProductos.clearSelection();
                producto = c.getIdProfuctoDefecto();
            }

//            mrv = new MyiReportVisor(System.getProperty("user.dir") + "\\reportes\\BoletaEntradaPorPersona.jrxml", parametros);
//            mrv.exportarAPdf();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnCobrarActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        String captura = txtNumPersonas.getText() + 0;
        txtNumPersonas.setText(captura);
        lblProducto.setText(prodGeneral);
        txtTotalCobrar.setText("" + c.getPrecioGeneral() * Double.parseDouble(txtNumPersonas.getText()));
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        txtNumPersonas.setText("");
        txtTotalCobrar.setText("");
        lblProducto.setText("");
        producto = c.getIdProfuctoDefecto();
        tblProductos.clearSelection();
    }//GEN-LAST:event_btnDelActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        String captura = txtNumPersonas.getText() + 1;
        txtNumPersonas.setText(captura);
        lblProducto.setText(prodGeneral);
        txtTotalCobrar.setText("" + c.getPrecioGeneral() * Double.parseDouble(txtNumPersonas.getText()));
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        String captura = txtNumPersonas.getText() + 2;
        txtNumPersonas.setText(captura);
        lblProducto.setText(prodGeneral);
        txtTotalCobrar.setText("" + c.getPrecioGeneral() * Double.parseDouble(txtNumPersonas.getText()));
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        String captura = txtNumPersonas.getText() + 4;
        txtNumPersonas.setText(captura);
        lblProducto.setText(prodGeneral);
        txtTotalCobrar.setText("" + c.getPrecioGeneral() * Double.parseDouble(txtNumPersonas.getText()));
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        String captura = txtNumPersonas.getText() + 5;
        txtNumPersonas.setText(captura);
        lblProducto.setText(prodGeneral);
        txtTotalCobrar.setText("" + c.getPrecioGeneral() * Double.parseDouble(txtNumPersonas.getText()));
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        String captura = txtNumPersonas.getText() + 6;
        txtNumPersonas.setText(captura);
        lblProducto.setText(prodGeneral);
        txtTotalCobrar.setText("" + c.getPrecioGeneral() * Double.parseDouble(txtNumPersonas.getText()));
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        String captura = txtNumPersonas.getText() + 7;
        txtNumPersonas.setText(captura);
        lblProducto.setText(prodGeneral);
        txtTotalCobrar.setText("" + c.getPrecioGeneral() * Double.parseDouble(txtNumPersonas.getText()));
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        String captura = txtNumPersonas.getText() + 8;
        txtNumPersonas.setText(captura);
        lblProducto.setText(prodGeneral);
        txtTotalCobrar.setText("" + c.getPrecioGeneral() * Double.parseDouble(txtNumPersonas.getText()));
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        String captura = txtNumPersonas.getText() + 9;
        txtNumPersonas.setText(captura);
        lblProducto.setText(prodGeneral);
        txtTotalCobrar.setText("" + c.getPrecioGeneral() * Double.parseDouble(txtNumPersonas.getText()));
    }//GEN-LAST:event_btn9ActionPerformed

    private void txtTotalCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalCobrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalCobrarActionPerformed

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        // TODO add your handling code here:

        if (!txtNumPersonas.getText().trim().isEmpty()) {
            int fila = tblProductos.getSelectedRow();

            producto = Integer.parseInt(tblProductos.getValueAt(fila, 0).toString());

            double precio = Double.parseDouble(tblProductos.getValueAt(fila, 3).toString());
            double cantidad = Double.parseDouble(txtNumPersonas.getText());
            lblProducto.setText(tblProductos.getValueAt(fila, 1).toString());
            txtTotalCobrar.setText("" + (precio * cantidad));
        } else {
            JOptionPane.showMessageDialog(null, "INDIQUE CANTIDAD");
            tblProductos.clearSelection();
        }

    }//GEN-LAST:event_tblProductosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntradaGeneralVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup botonesOpcion;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnCobrar;
    private javax.swing.JButton btnDel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodProductoCover;
    private javax.swing.JLabel lblPrecioCover;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblProductoCover;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtCaja;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtNumPersonas;
    private javax.swing.JTextField txtTotalCobrar;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void titulos() {
        String titulos[] = {"COD", "PRODUCTO", "PRESENTACION", "PRECIO"};
        modelo = new DefaultTableModel(null, titulos);
        tblProductos.setModel(modelo);
    }

    private void cargarTablaProductos() throws SQLException {
        Conexion con = new Conexion();
        try {
            con.conectar();
            String sql = "SELECT productopresentacion.idproductopresentacion, producto.nombre,presentacion.descripcion ,productopresentacion.precio3\n"
                    + "FROM productopresentacion\n"
                    + "inner join producto on productopresentacion.idproducto = producto.idproducto\n"
                    + "inner join presentacion on productopresentacion.idpresentacion = presentacion.idpresentacion\n"
                    + "where stock3 = 1 and idalmacen = 2";

            PreparedStatement pst = con.getConexion().prepareStatement(sql);
            ResultSet res = pst.executeQuery();

            Object datos[] = new Object[4];

            while (res.next()) {
                datos[0] = res.getInt(1);
                datos[1] = res.getString(2);
                datos[2] = res.getString(3);
                datos[3] = res.getDouble(4);
                modelo.addRow(datos);
            }

            tblProductos.setModel(modelo);

            new ColumnasTablas().cuatroColumnas(tblProductos, 60, 450,180 ,80);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            con.cerrar();
        }
    }

    public boolean restarStock(double quantity) throws Exception {
        try {
            int fila = tblProductos.getSelectedRow();
            int id = 0;
            if (fila >= 0) {
                id = Integer.parseInt(tblProductos.getValueAt(fila, 0).toString());

            } else {

                id = producto;
            }

            System.out.println("id: " + id);
            ProductoPresentacionDAO pdao = new ProductoPresentacionDAO();
            double stock = pdao.getStockProductoPresentacion(id, 1) - quantity;//-------
            System.out.println(stock);
            pdao.modificar(id, stock, 1);//tercer parametro 1 => ventas reales ; 2=>nota de pedido

        } catch (Exception e) {
            throw e;
        }
        return false;
    }

    private int getPageSize() {
        int filas = 1;
        System.out.println("cantidad de filas: " + filas);
        int rowCount = 1;//FILAS DE GRACIA
        int fontSize = 7;//TAMAÑO DE LETRA DEL DETAIL
        int rowSize = fontSize + 2;//TAMAÑO DE LA FILA
        int caracteresPorLinea = 16;// CANTIDAD DE CARACTERES PARA QUE PASE A LA SIGTE LINEA
        for (int i = 0; i < filas; i++) {
            //String descripcionDeProducto = tbl_venta.getValueAt(i, 1).toString();
            rowCount += 1;//(1 + (int) (descripcionDeProducto.length() / caracteresPorLinea));
        }
        int cabecera = 170;
        int piePagina = 90;
//        int pageSize = (rowCount * rowSize) + cabecera + piePagina;
        int pageSize = (rowCount) + cabecera + piePagina;
        System.out.println("Cantidad de Filas finale:" + rowCount);
        System.out.println("pageSize:" + pageSize);
        return pageSize;
    }

    private int getPageSize(int filas, int fontSize, int cabecera, int piePagina) {
        /*Para el cover el valor de Filas es 1*/
        System.out.println("cantidad de filas: " + filas);
        int rowSize = fontSize + 2;//TAMAÑO DE LA FILA
        int caracteresPorLinea = 16;// CANTIDAD DE CARACTERES PARA QUE PASE A LA SIGTE LINEA
        int rowCount = 0;
        for (int i = 0; i < filas; i++) {
            //String descripcionDeProducto = tbl_venta.getValueAt(i, 1).toString();
            rowCount += 1;//(1 + (int) (descripcionDeProducto.length() / caracteresPorLinea));
        }
//        int pageSize = (rowCount * rowSize) + cabecera + piePagina;
        int pageSize = (rowCount * rowSize) + cabecera + piePagina;
        System.out.println("Cantidad de Filas finale:" + rowCount);
        System.out.println("pageSize:" + pageSize);
        return pageSize;
    }
}
