package Vista;

import Controlador.AbrirCajaControl;
import Controlador.Cronometro;
import Controlador.ManejadorFechas;
import Controlador.ProductoControl;
import Modelo.Venta;
import Modelo.VentaDAO;
import Modelo.VentaEntrada;
import Modelo.VentaEntradaDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Marce
 */
public class EntradaVipBox extends javax.swing.JInternalFrame {

    /**
     * Creates new form EntradaVipBox
     */
    public EntradaVipBox(String usuario) throws Exception {
        initComponents();
        txtUsuario.setText(usuario);
        txtFecha.setText(new ManejadorFechas().getFechaActual());
        new Cronometro().iniciarCronometro(txtHora);
        txtCaja.setText(new AbrirCajaControl().getCajaDeUsuario(usuario));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNumPersonas = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtCaja = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnCobrar = new javax.swing.JButton();
        txtTotalCobrar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbBox = new javax.swing.JCheckBox();
        cmbVip = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setTitle("ENTRADAS VIP - BOX");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNumPersonas.setEditable(false);
        txtNumPersonas.setBackground(new java.awt.Color(51, 51, 51));
        txtNumPersonas.setFont(new java.awt.Font("Dialog", 0, 60)); // NOI18N
        txtNumPersonas.setForeground(new java.awt.Color(255, 255, 255));
        txtNumPersonas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtNumPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 580, 110));

        jPanel8.setBackground(new java.awt.Color(0, 102, 153));
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("ENTRADAS");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 30));

        jLabel15.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("VIP - BOX");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, 30));

        jLabel18.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel18.setText("VIP - BOX");
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 20, -1, 30));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/billete.png"))); // NOI18N
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 70));

        txtFecha.setEditable(false);
        txtFecha.setBackground(new java.awt.Color(0, 102, 153));
        txtFecha.setForeground(new java.awt.Color(255, 255, 255));
        txtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFecha.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "FECHA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, 90, -1));

        txtHora.setEditable(false);
        txtHora.setBackground(new java.awt.Color(0, 102, 153));
        txtHora.setForeground(new java.awt.Color(255, 255, 255));
        txtHora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHora.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "HORA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 20, 90, -1));

        txtUsuario.setEditable(false);
        txtUsuario.setBackground(new java.awt.Color(0, 102, 153));
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "USUARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 140, -1));

        jLabel17.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel17.setText("ENTRADAS");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 20, -1, 30));

        txtCaja.setEditable(false);
        txtCaja.setBackground(new java.awt.Color(0, 102, 153));
        txtCaja.setForeground(new java.awt.Color(255, 255, 255));
        txtCaja.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCaja.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "CAJA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.add(txtCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 140, -1));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 70));

        jPanel6.setBackground(new java.awt.Color(0, 102, 153));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 0, 0));
        jLabel19.setText("DISCOTECK");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, -1, -1));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel12.setText("DISCOTECK");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(892, 0, -1, -1));

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("MISTER JUERGA");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, -1, -1));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel11.setText("MISTER JUERGA");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 0, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 740, 1180, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn7.setBackground(new java.awt.Color(0, 153, 0));
        btn7.setFont(new java.awt.Font("SansSerif", 1, 60)); // NOI18N
        btn7.setForeground(new java.awt.Color(255, 255, 255));
        btn7.setText("7");
        btn7.setBorder(null);
        btn7.setBorderPainted(false);
        btn7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn7.setFocusPainted(false);
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel2.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 150, 120));

        btn8.setBackground(new java.awt.Color(0, 153, 0));
        btn8.setFont(new java.awt.Font("SansSerif", 1, 60)); // NOI18N
        btn8.setForeground(new java.awt.Color(255, 255, 255));
        btn8.setText("8");
        btn8.setBorder(null);
        btn8.setBorderPainted(false);
        btn8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn8.setFocusPainted(false);
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel2.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 150, 120));

        btn9.setBackground(new java.awt.Color(0, 153, 0));
        btn9.setFont(new java.awt.Font("SansSerif", 1, 60)); // NOI18N
        btn9.setForeground(new java.awt.Color(255, 255, 255));
        btn9.setText("9");
        btn9.setBorder(null);
        btn9.setBorderPainted(false);
        btn9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn9.setFocusPainted(false);
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 150, 120));

        btn4.setBackground(new java.awt.Color(0, 153, 0));
        btn4.setFont(new java.awt.Font("SansSerif", 1, 60)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setText("4");
        btn4.setBorder(null);
        btn4.setBorderPainted(false);
        btn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn4.setFocusPainted(false);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 150, 120));

        btn5.setBackground(new java.awt.Color(0, 153, 0));
        btn5.setFont(new java.awt.Font("SansSerif", 1, 60)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 255, 255));
        btn5.setText("5");
        btn5.setBorder(null);
        btn5.setBorderPainted(false);
        btn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn5.setFocusPainted(false);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel2.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 150, 120));

        btn6.setBackground(new java.awt.Color(0, 153, 0));
        btn6.setFont(new java.awt.Font("SansSerif", 1, 60)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.setText("6");
        btn6.setBorder(null);
        btn6.setBorderPainted(false);
        btn6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn6.setFocusPainted(false);
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel2.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 150, 120));

        btn1.setBackground(new java.awt.Color(0, 153, 0));
        btn1.setFont(new java.awt.Font("SansSerif", 1, 60)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("1");
        btn1.setBorder(null);
        btn1.setBorderPainted(false);
        btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn1.setFocusPainted(false);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 150, 120));

        btn2.setBackground(new java.awt.Color(0, 153, 0));
        btn2.setFont(new java.awt.Font("SansSerif", 1, 60)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setText("2");
        btn2.setBorder(null);
        btn2.setBorderPainted(false);
        btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn2.setFocusPainted(false);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 150, 120));

        btn3.setBackground(new java.awt.Color(0, 153, 0));
        btn3.setFont(new java.awt.Font("SansSerif", 1, 60)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setText("3");
        btn3.setBorder(null);
        btn3.setBorderPainted(false);
        btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn3.setFocusPainted(false);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 150, 120));

        btn0.setBackground(new java.awt.Color(0, 153, 0));
        btn0.setFont(new java.awt.Font("SansSerif", 1, 60)); // NOI18N
        btn0.setForeground(new java.awt.Color(255, 255, 255));
        btn0.setText("0");
        btn0.setBorder(null);
        btn0.setBorderPainted(false);
        btn0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn0.setFocusPainted(false);
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel2.add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 150, 120));

        btnDel.setBackground(new java.awt.Color(255, 0, 0));
        btnDel.setFont(new java.awt.Font("SansSerif", 1, 60)); // NOI18N
        btnDel.setForeground(new java.awt.Color(255, 255, 255));
        btnDel.setText("x");
        btnDel.setBorder(null);
        btnDel.setBorderPainted(false);
        btnDel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDel.setFocusPainted(false);
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        jPanel2.add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 150, 120));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("PRECIOS"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("GENERAL");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("VIP");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("BOX");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 120, -1));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 120, -1));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 120, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 540, 90));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 560, 670));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCobrar.setBackground(new java.awt.Color(255, 102, 0));
        btnCobrar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnCobrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCobrar.setText("COBRAR");
        btnCobrar.setBorder(null);
        btnCobrar.setBorderPainted(false);
        btnCobrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 580, 80));

        txtTotalCobrar.setEditable(false);
        txtTotalCobrar.setBackground(new java.awt.Color(51, 51, 51));
        txtTotalCobrar.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        txtTotalCobrar.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalCobrar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalCobrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jPanel3.add(txtTotalCobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 580, 110));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("TOTAL");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("S/.");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NUMERO DE PERSONAS");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        cmbBox.setBackground(new java.awt.Color(51, 51, 51));
        cmbBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cmbBox.setForeground(new java.awt.Color(255, 255, 255));
        cmbBox.setText("BOX");
        cmbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxActionPerformed(evt);
            }
        });
        jPanel3.add(cmbBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, -1, -1));

        cmbVip.setBackground(new java.awt.Color(51, 51, 51));
        cmbVip.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cmbVip.setForeground(new java.awt.Color(255, 255, 255));
        cmbVip.setText("VIP");
        cmbVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVipActionPerformed(evt);
            }
        });
        jPanel3.add(cmbVip, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 570, 220));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 620, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        String captura = txtNumPersonas.getText() + 7;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
        //txtCovers.setText("" + new ProductoControl().covers(2, numPersonas));
        //txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
        //int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
//        txtTotalCobrar.setText("" + new ProductoControl().total(cantCovers, cantPersonas, 10, 5));
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        String captura = txtNumPersonas.getText() + 8;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
        //txtCovers.setText("" + new ProductoControl().covers(2, numPersonas));
        //txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
        //int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
//        txtTotalCobrar.setText("" + new ProductoControl().total(cantCovers, cantPersonas, 10, 5));
        //txtCovers.setText(""+(cover*8));
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        String captura = txtNumPersonas.getText() + 9;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
//        txtCovers.setText("" + new ProductoControl().covers(2, numPersonas));
//        txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
//        int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
//        txtTotalCobrar.setText("" + new ProductoControl().total(cantCovers, cantPersonas, 10, 5));
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        String captura = txtNumPersonas.getText() + 4;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
//        txtCovers.setText("" + new ProductoControl().covers(2, numPersonas));
//        txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
//        int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
//        txtTotalCobrar.setText("" + new ProductoControl().total(cantCovers, cantPersonas, 10, 5));
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        String captura = txtNumPersonas.getText() + 5;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
//        txtCovers.setText("" + new ProductoControl().covers(2, numPersonas));
//        txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
//        int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
//        txtTotalCobrar.setText("" + new ProductoControl().total(cantCovers, cantPersonas, 10, 5));
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        String captura = txtNumPersonas.getText() + 6;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
//        txtCovers.setText("" + new ProductoControl().covers(2, numPersonas));
//        txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
//        int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
//        txtTotalCobrar.setText("" + new ProductoControl().total(cantCovers, cantPersonas, 10, 5));
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        String captura = txtNumPersonas.getText() + 1;
        txtNumPersonas.setText(captura);
        //btnAgregar.setEnabled(true);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
//        txtCovers.setText("" + new ProductoControl().covers(2, numPersonas));
//        txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
//        int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
//        txtTotalCobrar.setText("" + new ProductoControl().total(cantCovers, cantPersonas, 10, 5));
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        String captura = txtNumPersonas.getText() + 2;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
//        txtCovers.setText("" + new ProductoControl().covers(2, numPersonas));
//        txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
//        int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
//        txtTotalCobrar.setText("" + new ProductoControl().total(cantCovers, cantPersonas, 10, 5));
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        String captura = txtNumPersonas.getText() + 3;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
//        txtCovers.setText("" + new ProductoControl().covers(2, numPersonas));
//        txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
//        int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
//        txtTotalCobrar.setText("" + new ProductoControl().total(cantCovers, cantPersonas, 10, 5));
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        String captura = txtNumPersonas.getText() + 0;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
//        txtCovers.setText("" + new ProductoControl().covers(2, numPersonas));
//        txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
//        int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
//        txtTotalCobrar.setText("" + new ProductoControl().total(cantCovers, cantPersonas, 10, 5));
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        txtNumPersonas.setText("");
//        txtCovers.setText("");
        txtTotalCobrar.setText("");
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarActionPerformed
        try {
            String fec = new ManejadorFechas().getFechaActualMySQL();
            String hora = new ManejadorFechas().getHoraActual();
            int idCliente = 1;
            int idUsuario = 1;
            int idComprobante = 1;
            int estado = 1;
            int idCaja=1;
            //Registrar el comprobante

            //primero se registra la venta
            Venta v = new Venta(fec, hora, idUsuario, idCliente, idComprobante,estado,idCaja);
            VentaDAO vdao = new VentaDAO();
            vdao.registrar(v);
            //segundo se registra las entradas
            VentaEntrada ve = new VentaEntrada();
            int cantVentas = new VentaDAO().listar().size();
            if (cantVentas == 0) {
                cantVentas = 1;
            } else {
                cantVentas += 1;
            }
            ve.setNumPersonas(Integer.parseInt(txtNumPersonas.getText()));
//            ve.setNumCovers(Integer.parseInt(txtCovers.getText()));
            ve.setTotal(Double.parseDouble(txtTotalCobrar.getText()));
            ve.setTipoEntrada(""+1);
            ve.setIdVenta(cantVentas);

            VentaEntradaDAO vedao = new VentaEntradaDAO();
            vedao.registrar(ve);
            JOptionPane.showMessageDialog(rootPane, "VENTA REGISTRADA");

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnCobrarActionPerformed

    private void cmbBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxActionPerformed
        if (cmbBox.isSelected()) {
            try {
//                new ProductoControl().cargarCombo(cmbProductos);
//                cmbProductos.setEnabled(true);                
                cmbVip.setEnabled(false);
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        } else {
//            cmbProductos.setEnabled(false);
            cmbVip.setEnabled(true);
        }
    }//GEN-LAST:event_cmbBoxActionPerformed

    private void cmbVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVipActionPerformed
        if (cmbVip.isSelected()) {
            cmbBox.setEnabled(false);
//            cmbProductos.setEnabled(false);
//            int cantCovers = Integer.parseInt(txtCovers.getText());
            int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
//            txtTotalCobrar.setText("" + new ProductoControl().total(cantCovers, cantPersonas, 20, 10));
        } else {
            cmbBox.setEnabled(true);
//            cmbProductos.setEnabled(true);
//            int cantCovers = Integer.parseInt(txtCovers.getText());
            int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
//            txtTotalCobrar.setText("" + new ProductoControl().total(cantCovers, cantPersonas, 10, 5));
        }
    }//GEN-LAST:event_cmbVipActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnCobrar;
    private javax.swing.JButton btnDel;
    private javax.swing.JCheckBox cmbBox;
    private javax.swing.JCheckBox cmbVip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField txtCaja;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtNumPersonas;
    private javax.swing.JTextField txtTotalCobrar;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
