package Vista;

import Controlador.AbrirCajaControl;
import Controlador.Cronometro;
import Controlador.ProductoControl;
import Controlador.ManejadorFechas;
import Controlador.MyiReportVisor;
import Controlador.VentaEntradaControl;
import Modelo.Comprobante;
import Modelo.Venta;
import Modelo.VentaDAO;
import Modelo.VentaEntrada;
import Modelo.VentaEntradaDAO;
import java.awt.Color;
import java.io.IOException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

public class EntradaPorPersona extends javax.swing.JFrame {

    MyiReportVisor mrv;
    HashMap parametros = new HashMap();
    double costoGeneral = 10;
//    double costoVIP = 12;

    //double cover = 10.00;
    public EntradaPorPersona(String usuario) throws Exception {

        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
        this.setBackground(Color.WHITE);
        txtUsuario.setText(usuario);
        txtFecha.setText(new ManejadorFechas().getFechaActual());
        new Cronometro().iniciarCronometro(txtHora);
        txtCaja.setText(new AbrirCajaControl().getCajaDeUsuario(usuario));
        btn_mas.setEnabled(false);
        btn_menos.setEnabled(false);
        jcbChicas.setEnabled(false);
        jcbCerveza.setEnabled(false);

    }

    public EntradaPorPersona() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtCaja = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnCobrar = new javax.swing.JButton();
        txtTotalCobrar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCovers = new javax.swing.JTextField();
        btn_mas = new javax.swing.JButton();
        btn_menos = new javax.swing.JButton();
        txtNumPersonas = new javax.swing.JTextField();
        jcbChicas = new javax.swing.JCheckBox();
        jcbCerveza = new javax.swing.JCheckBox();
        lblLogo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ENTRADAS");
        setBounds(new java.awt.Rectangle(0, 0, 1000, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 51, 51));
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("ENTRADAS");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 30));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/billete.png"))); // NOI18N
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 70));

        txtFecha.setEditable(false);
        txtFecha.setBackground(new java.awt.Color(255, 51, 51));
        txtFecha.setForeground(new java.awt.Color(255, 255, 255));
        txtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFecha.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "FECHA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1720, 20, 90, -1));

        txtHora.setEditable(false);
        txtHora.setBackground(new java.awt.Color(255, 51, 51));
        txtHora.setForeground(new java.awt.Color(255, 255, 255));
        txtHora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHora.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "HORA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 20, 90, -1));

        txtUsuario.setEditable(false);
        txtUsuario.setBackground(new java.awt.Color(255, 51, 51));
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "USUARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 20, 140, -1));

        jLabel17.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel17.setText("ENTRADAS");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 20, -1, 30));

        txtCaja.setEditable(false);
        txtCaja.setBackground(new java.awt.Color(255, 51, 51));
        txtCaja.setForeground(new java.awt.Color(255, 255, 255));
        txtCaja.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCaja.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "CAJA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.add(txtCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 140, -1));

        jLabel16.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("GENERAL");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 20, -1, 30));

        jLabel18.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel18.setText("GENERAL");
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, 30));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 70));

        jPanel6.setBackground(new java.awt.Color(255, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 0, 0));
        jLabel19.setText("DISCOTECK");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(932, 0, -1, -1));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel12.setText("DISCOTECK");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, -1, -1));

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("MISTER JUERGA");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, -1, -1));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel11.setText("MISTER JUERGA");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 0, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1020, 1920, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn7.setBackground(new java.awt.Color(0, 153, 0));
        btn7.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn7.setForeground(new java.awt.Color(255, 255, 255));
        btn7.setText("7");
        btn7.setBorderPainted(false);
        btn7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn7.setFocusPainted(false);
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel2.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 210, 180));

        btn8.setBackground(new java.awt.Color(0, 153, 0));
        btn8.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn8.setForeground(new java.awt.Color(255, 255, 255));
        btn8.setText("8");
        btn8.setBorderPainted(false);
        btn8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn8.setFocusPainted(false);
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel2.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 210, 180));

        btn4.setBackground(new java.awt.Color(0, 153, 0));
        btn4.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setText("4");
        btn4.setBorderPainted(false);
        btn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn4.setFocusPainted(false);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 210, 180));

        btn5.setBackground(new java.awt.Color(0, 153, 0));
        btn5.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 255, 255));
        btn5.setText("5");
        btn5.setBorderPainted(false);
        btn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn5.setFocusPainted(false);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel2.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 210, 180));

        btn6.setBackground(new java.awt.Color(0, 153, 0));
        btn6.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.setText("6");
        btn6.setBorderPainted(false);
        btn6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn6.setFocusPainted(false);
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel2.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 210, 180));

        btn2.setBackground(new java.awt.Color(0, 153, 0));
        btn2.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setText("2");
        btn2.setBorderPainted(false);
        btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn2.setFocusPainted(false);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 210, 180));

        btn3.setBackground(new java.awt.Color(0, 153, 0));
        btn3.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setText("3");
        btn3.setBorderPainted(false);
        btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn3.setFocusPainted(false);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 210, 180));

        btn0.setBackground(new java.awt.Color(0, 153, 0));
        btn0.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn0.setForeground(new java.awt.Color(255, 255, 255));
        btn0.setText("0");
        btn0.setBorderPainted(false);
        btn0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn0.setFocusPainted(false);
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel2.add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 620, 210, 180));

        btnDel.setBackground(new java.awt.Color(255, 0, 0));
        btnDel.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btnDel.setForeground(new java.awt.Color(255, 255, 255));
        btnDel.setText("x");
        btnDel.setBorderPainted(false);
        btnDel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDel.setFocusPainted(false);
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        jPanel2.add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 210, 180));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("PRECIOS"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("GENERAL");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("VIP");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("BOX");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 120, -1));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 120, -1));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 120, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 840, 540, 90));

        btn1.setBackground(new java.awt.Color(0, 153, 0));
        btn1.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("1");
        btn1.setBorderPainted(false);
        btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn1.setFocusPainted(false);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 210, 180));

        btn9.setBackground(new java.awt.Color(0, 153, 0));
        btn9.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn9.setForeground(new java.awt.Color(255, 255, 255));
        btn9.setText("9");
        btn9.setBorderPainted(false);
        btn9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn9.setFocusPainted(false);
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 210, 180));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 720, 940));

        jPanel3.setBackground(new java.awt.Color(51, 153, 0));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCobrar.setBackground(new java.awt.Color(255, 102, 0));
        btnCobrar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnCobrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCobrar.setText("COBRAR");
        btnCobrar.setBorderPainted(false);
        btnCobrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 770, 560, 120));

        txtTotalCobrar.setEditable(false);
        txtTotalCobrar.setBackground(new java.awt.Color(51, 153, 0));
        txtTotalCobrar.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        txtTotalCobrar.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalCobrar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalCobrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        txtTotalCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalCobrarActionPerformed(evt);
            }
        });
        jPanel3.add(txtTotalCobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 590, 650, 130));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("TOTAL");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("S/.");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NUMERO DE PERSONAS");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 290, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("COVERS");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 110, 50));

        txtCovers.setEditable(false);
        txtCovers.setBackground(new java.awt.Color(51, 153, 0));
        txtCovers.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtCovers.setForeground(new java.awt.Color(255, 255, 255));
        txtCovers.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCovers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCoversActionPerformed(evt);
            }
        });
        jPanel3.add(txtCovers, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 350, 100));

        btn_mas.setBackground(new java.awt.Color(0, 153, 255));
        btn_mas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/flecha-hacia-arriba5.png"))); // NOI18N
        btn_mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_masActionPerformed(evt);
            }
        });
        jPanel3.add(btn_mas, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 280, 80, 90));

        btn_menos.setBackground(new java.awt.Color(0, 153, 255));
        btn_menos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/flecha-hacia-abajo.png"))); // NOI18N
        btn_menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menosActionPerformed(evt);
            }
        });
        jPanel3.add(btn_menos, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 390, 80, 90));

        txtNumPersonas.setEditable(false);
        txtNumPersonas.setBackground(new java.awt.Color(51, 153, 0));
        txtNumPersonas.setFont(new java.awt.Font("Dialog", 0, 60)); // NOI18N
        txtNumPersonas.setForeground(new java.awt.Color(255, 255, 255));
        txtNumPersonas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(txtNumPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 650, 110));

        jcbChicas.setBackground(new java.awt.Color(51, 153, 0));
        jcbChicas.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        jcbChicas.setForeground(new java.awt.Color(255, 255, 255));
        jcbChicas.setText("CHICAS");
        jcbChicas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chica1.png"))); // NOI18N
        jcbChicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbChicasActionPerformed(evt);
            }
        });
        jPanel3.add(jcbChicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 250, 70));

        jcbCerveza.setBackground(new java.awt.Color(51, 153, 0));
        jcbCerveza.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        jcbCerveza.setForeground(new java.awt.Color(255, 255, 255));
        jcbCerveza.setText("CERVEZA");
        jcbCerveza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerveza (1).png"))); // NOI18N
        jcbCerveza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCervezaActionPerformed(evt);
            }
        });
        jPanel3.add(jcbCerveza, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 280, 70));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/idosftlogo_opt.png")));
        jPanel3.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 130, -1));

        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("IDSOFT S.A.C.");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 170, 60));

        jLabel5.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("\"Usted no se adecua al Software ,\n el Software se adecua a Usted\"");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 400, 70));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, 1200, 950));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        String captura = txtNumPersonas.getText() + 3;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
        txtCovers.setText("" + new ProductoControl().covers(1, numPersonas));
        //txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
        int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
        txtTotalCobrar.setText("" + new ProductoControl().total(cantCovers, costoGeneral));
        btn_mas.setEnabled(true);
        btn_menos.setEnabled(true);
        jcbChicas.setEnabled(true);
        jcbCerveza.setEnabled(true);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btnCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarActionPerformed
        try {
            //capturo datos
            String fec = new ManejadorFechas().getFechaActualMySQL();
            String hora = new ManejadorFechas().getHoraActual();
            int idCliente = 1;
            int idUsuario = new VentaEntradaControl().getIdUsuario(txtUsuario.getText());
            int idComprobante = 1;
            int estado = 1;
            int idCaja = 1;
            //Registrar el comprobante
            new VentaEntradaControl().regComprobante(fec, txtUsuario.getText(), "ENTRADA", Integer.parseInt(txtNumPersonas.getText()), Double.parseDouble(txtTotalCobrar.getText()), "12345678912", "JR AYACUCHO 760", "EFECTIVO", Double.parseDouble(txtTotalCobrar.getText()), idComprobante);

            //registrar la venta
            Venta v = new Venta(fec, hora, idUsuario, idCliente, idComprobante, estado, idCaja);
            VentaDAO vdao = new VentaDAO();
            vdao.registrar(v);
            //segundo se registra las entradas
            VentaEntrada ve = new VentaEntrada();
            int prod = 1;
            int idVenta = new VentaEntradaControl().getIdDeUltimaVentaRegistrada();
            System.out.println("ultima venta: "+idVenta);
            ve.setNumPersonas(Integer.parseInt(txtNumPersonas.getText()));
            ve.setNumCovers(Integer.parseInt(txtCovers.getText()));
            ve.setTotal(Double.parseDouble(txtTotalCobrar.getText()));
            ve.setTipoEntrada("ENTRADA GENERAL");            
            ve.setIdVenta(idVenta);
            if (jcbCerveza.isSelected()) {
                prod = 2;
            }else{
                prod = 1;
            }
            ve.setProd(prod);

            VentaEntradaDAO vedao = new VentaEntradaDAO();
            if (vedao.registrar(ve)) {
                boolean printChicas = jcbChicas.isSelected();
//                JOptionPane.showMessageDialog(rootPane, "VENTA REGISTRADA");
                parametros.put("nom_cajero", txtUsuario.getText());
                parametros.put("id_venta", idVenta);
                mrv = new MyiReportVisor(System.getProperty("user.dir") + "\\reportes\\boleta.jrxml", parametros, getPageSize());
                mrv.setNombreArchivo("BoletaEntrada");
                if(!printChicas)
                    mrv.exportarADocxConCopia("boletas.docx");
                
                HashMap par2 = new HashMap();
                System.out.println("Imprimiendo Cover");
                par2.put("nroComprobante", idVenta);
                String flagCover = "COVER";
                if (jcbCerveza.isSelected()){
                    flagCover = "CERVEZA";
                }else{
                    flagCover = "COVER";
                }
                par2.put("nombreCover", flagCover);
                MyiReportVisor mrv2 = new MyiReportVisor(System.getProperty("user.dir") + "\\reportes\\coversNormalT1.jrxml", par2, getPageSize(1 , 28 ,20 , 33));
                mrv2.setNombreArchivo("Cover Cerveza");
                int numerodeCopias = ve.getNumCovers();
                for(int i = 1 ; i<= numerodeCopias; i++ ){
                    if(!printChicas)
                    mrv2.exportarADocxConCopia("covers"+i+".docx");
                }
                txtNumPersonas.setText("");
                txtCovers.setText("");
                txtTotalCobrar.setText("");
                btn_mas.setEnabled(false);
                btn_menos.setEnabled(false);
                jcbChicas.setEnabled(false);
                jcbChicas.setSelected(false);
                jcbCerveza.setEnabled(false);
                jcbCerveza.setSelected(false);
            } else {
            }

//            mrv = new MyiReportVisor(System.getProperty("user.dir") + "\\reportes\\BoletaEntradaPorPersona.jrxml", parametros);
//            mrv.exportarAPdf();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnCobrarActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        String captura = txtNumPersonas.getText() + 0;
        txtNumPersonas.setText(captura);
        //CAPTURAR EL PRECIO DE LAS ENTRADAS GENERALES
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
        txtCovers.setText("" + new ProductoControl().covers(1, numPersonas));
        //txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
        int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
        txtTotalCobrar.setText("" + new ProductoControl().total(cantCovers, costoGeneral));
        btn_mas.setEnabled(true);
        btn_menos.setEnabled(true);
        jcbChicas.setEnabled(true);
        jcbCerveza.setEnabled(true);
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        txtNumPersonas.setText("");
        txtCovers.setText("");
        txtTotalCobrar.setText("");
        btn_mas.setEnabled(false);
        btn_menos.setEnabled(false);
        jcbCerveza.setEnabled(false);
        jcbChicas.setEnabled(false);

    }//GEN-LAST:event_btnDelActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        String captura = txtNumPersonas.getText() + 1;
        txtNumPersonas.setText(captura);
        //btnAgregar.setEnabled(true);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
        txtCovers.setText("" + new ProductoControl().covers(1, numPersonas));
        //txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
        int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());        
        txtTotalCobrar.setText("" + new ProductoControl().total(cantCovers, costoGeneral));//precio de cover se debe jalar de base de datosvvvv
        btn_mas.setEnabled(true);
        btn_menos.setEnabled(true);
        jcbChicas.setEnabled(true);
        jcbCerveza.setEnabled(true);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        String captura = txtNumPersonas.getText() + 2;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
        txtCovers.setText("" + new ProductoControl().covers(1, numPersonas));
        //txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
        int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
        txtTotalCobrar.setText("" + new ProductoControl().total(cantCovers, costoGeneral));
        btn_mas.setEnabled(true);
        btn_menos.setEnabled(true);
        jcbCerveza.setEnabled(true);
        jcbChicas.setEnabled(true);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        String captura = txtNumPersonas.getText() + 4;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
        txtCovers.setText("" + new ProductoControl().covers(1, numPersonas));
        //txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
        int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
        txtTotalCobrar.setText("" + new ProductoControl().total(cantCovers, costoGeneral));
        btn_mas.setEnabled(true);
        btn_menos.setEnabled(true);
        jcbChicas.setEnabled(true);
        jcbCerveza.setEnabled(true);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        String captura = txtNumPersonas.getText() + 5;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
        txtCovers.setText("" + new ProductoControl().covers(1, numPersonas));
        //txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
        int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
        txtTotalCobrar.setText("" + new ProductoControl().total(cantCovers, costoGeneral));
        btn_mas.setEnabled(true);
        btn_menos.setEnabled(true);
        jcbChicas.setEnabled(true);
        jcbCerveza.setEnabled(true);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        String captura = txtNumPersonas.getText() + 6;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
        txtCovers.setText("" + new ProductoControl().covers(1, numPersonas));
        //txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
        int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
        txtTotalCobrar.setText("" + new ProductoControl().total(cantCovers, costoGeneral));
        btn_mas.setEnabled(true);
        btn_menos.setEnabled(true);
        jcbChicas.setEnabled(true);
        jcbCerveza.setEnabled(true);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        String captura = txtNumPersonas.getText() + 7;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
        txtCovers.setText("" + new ProductoControl().covers(1, numPersonas));
        //txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
        int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
        txtTotalCobrar.setText("" + new ProductoControl().total(cantCovers, costoGeneral));
        btn_mas.setEnabled(true);
        btn_menos.setEnabled(true);
        jcbChicas.setEnabled(true);
        jcbCerveza.setEnabled(true);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        String captura = txtNumPersonas.getText() + 8;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
        txtCovers.setText("" + new ProductoControl().covers(1, numPersonas));
        //txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
        int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
        txtTotalCobrar.setText("" + new ProductoControl().total(cantCovers, costoGeneral));
        //txtCovers.setText(""+(cover*8));
        btn_mas.setEnabled(true);
        btn_menos.setEnabled(true);
        jcbChicas.setEnabled(true);
        jcbCerveza.setEnabled(true);
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        String captura = txtNumPersonas.getText() + 9;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
        txtCovers.setText("" + new ProductoControl().covers(1, numPersonas));
        //txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
        int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
        txtTotalCobrar.setText("" + new ProductoControl().total(cantCovers, costoGeneral));
        btn_mas.setEnabled(true);
        btn_menos.setEnabled(true);
        jcbChicas.setEnabled(true);
        jcbCerveza.setEnabled(true);
    }//GEN-LAST:event_btn9ActionPerformed

    private void txtCoversActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCoversActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCoversActionPerformed

    private void btn_masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_masActionPerformed
        int cover = Integer.parseInt(txtCovers.getText());
        cover += 1;
        txtCovers.setText(cover + "");
        int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
        txtTotalCobrar.setText("" + new ProductoControl().total(cantCovers, costoGeneral));

    }//GEN-LAST:event_btn_masActionPerformed

    private void btn_menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menosActionPerformed
        int cover = Integer.parseInt(txtCovers.getText());
        cover -= 1;
        txtCovers.setText(cover + "");
        int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
        txtTotalCobrar.setText("" + new ProductoControl().total(cantCovers, costoGeneral));

    }//GEN-LAST:event_btn_menosActionPerformed

    private void jcbChicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbChicasActionPerformed
        int cantCovers = Integer.parseInt(txtCovers.getText());
        if (jcbChicas.isSelected()) {
            txtTotalCobrar.setText("" + new ProductoControl().total(cantCovers, 0));
        } else {
            txtTotalCobrar.setText("" + new ProductoControl().total(cantCovers, costoGeneral));
        }

    }//GEN-LAST:event_jcbChicasActionPerformed

    private void jcbCervezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCervezaActionPerformed
       int cantCovers = Integer.parseInt(txtCovers.getText());
        if (!jcbCerveza.isSelected()) {
            txtTotalCobrar.setText("" + new ProductoControl().total(cantCovers, costoGeneral));//precio de cover se debe jalar de base de datosvvvv                        
        }else{
            txtTotalCobrar.setText("" + new ProductoControl().total(cantCovers, costoGeneral + 2));//precio de cover se debe jalar de base de datosvvvv
            jcbCerveza.setBackground(Color.BLACK);
        }
    }//GEN-LAST:event_jcbCervezaActionPerformed

    private void txtTotalCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalCobrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalCobrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntradaPorPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnCobrar;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btn_mas;
    private javax.swing.JButton btn_menos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JCheckBox jcbCerveza;
    private javax.swing.JCheckBox jcbChicas;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JTextField txtCaja;
    private javax.swing.JTextField txtCovers;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtNumPersonas;
    private javax.swing.JTextField txtTotalCobrar;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private int getPageSize() {
        int filas = 1;
        System.out.println("cantidad de filas: " + filas);
        int rowCount = 1;//FILAS DE GRACIA
        int fontSize = 7;//TAMAÑO DE LETRA DEL DETAIL
        int rowSize = fontSize + 2;//TAMAÑO DE LA FILA
        int caracteresPorLinea = 16;// CANTIDAD DE CARACTERES PARA QUE PASE A LA SIGTE LINEA
        for (int i = 0; i < filas; i++) {
            //String descripcionDeProducto = tbl_venta.getValueAt(i, 1).toString();
            rowCount += 1;//(1 + (int) (descripcionDeProducto.length() / caracteresPorLinea));
        }
        int cabecera = 170;
        int piePagina = 90;
//        int pageSize = (rowCount * rowSize) + cabecera + piePagina;
        int pageSize = (rowCount) + cabecera + piePagina;
        System.out.println("Cantidad de Filas finale:" + rowCount);
        System.out.println("pageSize:" + pageSize);
        return pageSize;
    }
    
    private int getPageSize(int filas,  int fontSize,int cabecera, int piePagina) {
        /*Para el cover el valor de Filas es 1*/
        System.out.println("cantidad de filas: " + filas);
        int rowSize = fontSize + 2;//TAMAÑO DE LA FILA
        int caracteresPorLinea = 16;// CANTIDAD DE CARACTERES PARA QUE PASE A LA SIGTE LINEA
        int rowCount = 0;
        for (int i = 0; i < filas; i++) {
            //String descripcionDeProducto = tbl_venta.getValueAt(i, 1).toString();
            rowCount += 1;//(1 + (int) (descripcionDeProducto.length() / caracteresPorLinea));
        }
//        int pageSize = (rowCount * rowSize) + cabecera + piePagina;
        int pageSize = (rowCount * rowSize) + cabecera + piePagina;
        System.out.println("Cantidad de Filas finale:" + rowCount);
        System.out.println("pageSize:" + pageSize);
        return pageSize;
    }
}
