/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.AbrirCajaControl;
import Controlador.MenuControl;
import Modelo.FlujoCaja;
import Modelo.MySQLDAO.FlujoCajaDAO;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu(String Usuario) throws Exception {
        setUndecorated(true);
        initComponents();
        cargarDatos(Usuario);
    }

    public Menu() {
    }

    public void cargarDatos(String Usuario) throws Exception {
        try {
            Color c = new Color(255,255,255);
            this.setBackground(c);
            setLocationRelativeTo(null);
            setExtendedState(MAXIMIZED_BOTH);
            lbl_Usuario.setText(Usuario);
            lbl_caja.setText(new MenuControl().getCajaDeUsuario(Usuario));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnEntradaGeneral = new javax.swing.JButton();
        btnEntradaVip = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblSalir = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_caja = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_Usuario = new javax.swing.JLabel();
        lblImg = new javax.swing.JLabel();
        btnGastos = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Cash_Register_100px.png"))); // NOI18N
        jButton4.setText("CIERRE");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 620, 330, 220));

        jButton5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Delete_Ticket_100px.png"))); // NOI18N
        jButton5.setText("ANULACIONES");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 620, 330, 220));

        jButton6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Purchase_Order_100px.png"))); // NOI18N
        jButton6.setText("LISTA DE VENTAS");
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 620, 330, 220));

        btnEntradaGeneral.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnEntradaGeneral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Two_Tickets_100px.png"))); // NOI18N
        btnEntradaGeneral.setText("VENTA GENERAL");
        btnEntradaGeneral.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEntradaGeneral.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEntradaGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaGeneralActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntradaGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 330, 220));

        btnEntradaVip.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnEntradaVip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_POS_Terminal_100px.png"))); // NOI18N
        btnEntradaVip.setText("VENTA VIP");
        btnEntradaVip.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEntradaVip.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEntradaVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaVipActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntradaVip, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 390, 330, 220));

        jButton3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Wallet_100px.png"))); // NOI18N
        jButton3.setText("APERTURA");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 330, 220));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_List_100px.png"))); // NOI18N
        jLabel2.setText("MENU  DE ENTRADAS");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 490, 90));

        lblSalir.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblSalir.setForeground(new java.awt.Color(51, 51, 51));
        lblSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Close_Window_100px.png"))); // NOI18N
        lblSalir.setText("SALIR");
        lblSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
        });
        getContentPane().add(lblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1700, 10, 210, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 130, 30));

        lbl_caja.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbl_caja.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(lbl_caja, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 330, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Caja:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 130, 30));

        lbl_Usuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbl_Usuario.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(lbl_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 330, 30));

        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/girlDJ.png"))); // NOI18N
        lblImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImgMouseClicked(evt);
            }
        });
        getContentPane().add(lblImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 880, 210, 160));

        btnGastos.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnGastos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Cash_in_Hand_100px.png"))); // NOI18N
        btnGastos.setText("GASTOS");
        btnGastos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGastos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGastosActionPerformed(evt);
            }
        });
        getContentPane().add(btnGastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 390, 330, 220));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 470, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String usuario = lbl_Usuario.getText();
            AbrirCaja ac = new AbrirCaja(usuario);
            ac.setVisible(true);
            //dispose();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnEntradaVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaVipActionPerformed
        try {

            if (lbl_caja.getText().equals("ENTRADA VIP")) {
                int flag = 0;
                int idFlujoCaja = new FlujoCajaDAO().getIdFlujo(new AbrirCajaControl().getIdUsuario(lbl_Usuario.getText()), new AbrirCajaControl().getIdCaja(lbl_caja.getText()));
                FlujoCajaDAO fcdao = new FlujoCajaDAO();
                for (FlujoCaja fc : fcdao.Listar()) {
                    if (fc.getIdFlujoCaja() == idFlujoCaja && fc.getEstado().equals("1")) {
                        flag++;
                    }
                }
                if (flag > 0) {
                    String usuario = lbl_Usuario.getText();
                    EntradaVipBox evip = new EntradaVipBox(usuario);
                    evip.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "DEBE APERTURAR CAJA PARA REALIZAR VENTAS");
                }
            } else {
                JOptionPane.showMessageDialog(null, "ESTA ASIGNADO A ENTRADA GENERAL, NO PUEDE RELIZAR VENTAS DE ENTRADA VIP");
            }

            //dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
        }

//        try {
//
//            if (lbl_caja.getText().equals("ENTRADA VIP")) {
//                String usuario = lbl_Usuario.getText();
//                EntradaVipBox evip = new EntradaVipBox(usuario);
//                evip.setVisible(true);
//            } else {
//                JOptionPane.showMessageDialog(null, "ESTA ASIGNADO A ENTRADA GENERAL, NO PUEDE RELIZAR VENTAS VIP");
//            }
//            //dispose();
//        } catch (Exception e) {
//            System.out.println(e.getMessage());
//        }
    }//GEN-LAST:event_btnEntradaVipActionPerformed

    private void btnEntradaGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaGeneralActionPerformed
        try {

            if (lbl_caja.getText().equals("ENTRADA GENERAL") || lbl_caja.getText().equals("ENTRADA GENERAL 2")) {
                int flag = 0;
                int idFlujoCaja = new FlujoCajaDAO().getIdFlujo(new AbrirCajaControl().getIdUsuario(lbl_Usuario.getText()), new AbrirCajaControl().getIdCaja(lbl_caja.getText()));
                FlujoCajaDAO fcdao = new FlujoCajaDAO();
                for (FlujoCaja fc : fcdao.Listar()) {
                    if (fc.getIdFlujoCaja() == idFlujoCaja && fc.getEstado().equals("1")) {
                        flag++;
                    }
                }
                if (flag > 0) {
                    String usuario = lbl_Usuario.getText();
                    EntradaGeneralVista epp = new EntradaGeneralVista(usuario);
                    epp.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "DEBE APERTURAR CAJA PARA REALIZAR VENTAS");
                }
            } else {
                JOptionPane.showMessageDialog(null, "ESTA ASIGNADO A ENTRADAS VIP, NO PUEDE RELIZAR VENTAS DE ENTRADA GENERAL");
            }

            //dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnEntradaGeneralActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            if (lbl_caja.getText().equals("ENTRADA GENERAL") || lbl_caja.getText().equals("ENTRADA GENERAL 2")) {
                String usuario = lbl_Usuario.getText();
                ResumenEntradasGeneral le = new ResumenEntradasGeneral(usuario);
                le.setVisible(true);
            } else {
                String usuario = lbl_Usuario.getText();
                ResumenEntradasVIP le = new ResumenEntradasVIP(usuario);
                le.setVisible(true);
            }
            // dispose();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            String usuario = lbl_Usuario.getText();
            Anulaciones a = new Anulaciones(usuario);
            a.setVisible(true);
            //   dispose();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            String usuario = lbl_Usuario.getText();
            //validar si es entrada vip o entrada popular
            if (lbl_caja.getText().trim().equals("ENTRADA VIP")) {
                CerrarCajaVIP ccv = new CerrarCajaVIP(lbl_Usuario.getText());
                ccv.setVisible(true);
            } else {
                CerrarCaja cc = new CerrarCaja(usuario);
                cc.setVisible(true);
            }

            // dispose();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_lblSalirMouseClicked

    private void lblImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImgMouseClicked
        try {

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        try {

            if (lbl_caja.getText().equals("ENTRADA VIP")) {
                int flag = 0;
                int idFlujoCaja = new FlujoCajaDAO().getIdFlujo(new AbrirCajaControl().getIdUsuario(lbl_Usuario.getText()), new AbrirCajaControl().getIdCaja(lbl_caja.getText()));
                FlujoCajaDAO fcdao = new FlujoCajaDAO();
                for (FlujoCaja fc : fcdao.Listar()) {
                    if (fc.getIdFlujoCaja() == idFlujoCaja && fc.getEstado().equals("1")) {
                        flag++;
                    }
                }
                if (flag > 0) {
                    String usuario = lbl_Usuario.getText();
                    VipNotaPedido vnp = new VipNotaPedido(usuario);
                    vnp.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "DEBE APERTURAR CAJA PARA REALIZAR VENTAS");
                }
            } else {
                JOptionPane.showMessageDialog(null, "ESTA ASIGNADO A ENTRADAS VIP, NO PUEDE RELIZAR VENTAS DE ENTRADA GENERAL");
            }

            //dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_lblImgMouseClicked

    private void btnGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGastosActionPerformed
        try {

            int flag = 0;
            int idFlujoCaja = new FlujoCajaDAO().getIdFlujo(new AbrirCajaControl().getIdUsuario(lbl_Usuario.getText()), new AbrirCajaControl().getIdCaja(lbl_caja.getText()));
            FlujoCajaDAO fcdao = new FlujoCajaDAO();
            for (FlujoCaja fc : fcdao.Listar()) {
                if (fc.getIdFlujoCaja() == idFlujoCaja && fc.getEstado().equals("1")) {
                    flag++;
                }
            }
            if (flag > 0) {
                String usuario = lbl_Usuario.getText();
                Gastos g = new Gastos(usuario);
                g.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "DEBE APERTURAR CAJA PARA REGISTRAR GASTOS");
            }

            //dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnGastosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntradaGeneral;
    private javax.swing.JButton btnEntradaVip;
    private javax.swing.JButton btnGastos;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JLabel lbl_Usuario;
    private javax.swing.JLabel lbl_caja;
    // End of variables declaration//GEN-END:variables
}
