package Vista;

import Controlador.AbrirCajaControl;
import Controlador.CerrarCajaControl;
import Controlador.ColumnasTablas;
import Controlador.MyiReportVisor;
import Controlador.EntradaGeneralControl;
import Modelo.Conexion;
import Modelo.MySQLDAO.FlujoCajaDAO;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author g0by
 */
public class ResumenEntradasGeneral extends javax.swing.JFrame {

    DefaultTableModel modelo;
    MyiReportVisor mrv;
    HashMap parametros = new HashMap();

    public ResumenEntradasGeneral(String Usuario) throws Exception {

        initComponents();
        setLocationRelativeTo(null);

        try {
            txtUsuario.setText(Usuario);
            txtCaja.setText(new AbrirCajaControl().getCajaDeUsuario(Usuario));
            titulosColumnas();
            int idFlujoCaja = new FlujoCajaDAO().getIdFlujo(new CerrarCajaControl().getIdUsuario(Usuario), new CerrarCajaControl().getIdCaja(txtCaja.getText()));
            if (txtCaja.getText().equals("ENTRADA GENERAL")) {
                LlenarTablaBuscarProductos(idFlujoCaja,2);
            } else {
                LlenarTablaBuscarProductos(idFlujoCaja,6);
            }
            
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }

    }

    public ResumenEntradasGeneral() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEntradas = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtCaja = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblEntradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblEntradas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 880, 490));

        jPanel8.setBackground(new java.awt.Color(204, 51, 0));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("RESUMEN ENTRADA GENERAL");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, 30));

        txtHora.setEditable(false);
        txtHora.setBackground(new java.awt.Color(204, 51, 0));
        txtHora.setForeground(new java.awt.Color(255, 255, 255));
        txtHora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHora.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "HORA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, 140, -1));

        txtUsuario.setEditable(false);
        txtUsuario.setBackground(new java.awt.Color(204, 51, 0));
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setOpaque(false);
        txtUsuario.setRequestFocusEnabled(false);
        jPanel8.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 140, -1));

        jLabel31.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel31.setText("RESUMEN ENTRADA GENERAL");
        jPanel8.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 50, -1, 30));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/caja-registradora general.png"))); // NOI18N
        jPanel8.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 130));

        txtCaja.setEditable(false);
        txtCaja.setBackground(new java.awt.Color(204, 51, 0));
        txtCaja.setForeground(new java.awt.Color(255, 255, 255));
        txtCaja.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCaja.setOpaque(false);
        txtCaja.setRequestFocusEnabled(false);
        jPanel8.add(txtCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 140, -1));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 130));

        jPanel6.setBackground(new java.awt.Color(204, 51, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 0, 0));
        jLabel19.setText("DISCOTECK");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, -1, -1));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel12.setText("DISCOTECK");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 0, -1, -1));

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("MISTER JUERGA");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel6.setText("MISTER JUERGA");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 0, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 880, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResumenEntradasGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblEntradas;
    public javax.swing.JTextField txtCaja;
    public javax.swing.JTextField txtHora;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    public void titulosColumnas() {
        String cabecera[] = {"VENTA", "PRODUCTO", "MONTO"};
        modelo = new DefaultTableModel(null, cabecera);
        tblEntradas.setModel(modelo);
    }

    public void LlenarTablaBuscarProductos(int idFlujoCaja, int caja) throws Exception {
        Conexion con = new Conexion();
        try {
            con.conectar();
            
            String sql = null;
            
            if (caja == 2) {
                sql = "select entradageneral.identradageneral, producto.nombre, ventaentrada.total\n"
                    + "from entradageneral \n"
                    + "inner join ventaentrada on entradageneral.identradageneral = ventaentrada.venta_idventa\n"
                    + "inner join productopresentacion on ventaentrada.idproducto = productopresentacion.idproductopresentacion\n"
                    + "inner join producto on productopresentacion.idproducto = producto.idproducto\n"
                    + "where idflujocaja = ?";
            }else{
                sql = "select entradageneral2.identradageneral2, producto.nombre, ventaentrada2.total\n"
                    + "from entradageneral2 \n"
                    + "inner join ventaentrada2 on entradageneral2.identradageneral2 = ventaentrada2.venta_idventa\n"
                    + "inner join productopresentacion on ventaentrada2.idproducto = productopresentacion.idproductopresentacion\n"
                    + "inner join producto on productopresentacion.idproducto = producto.idproducto\n"
                    + "where idflujocaja = ?";
            }
            
            
            
            PreparedStatement pst = con.getConexion().prepareStatement(sql);
            pst.setInt(1, idFlujoCaja);
            ResultSet res = pst.executeQuery();
            
            Object datos[] = new Object[3];

            while (res.next()) {
                datos[0] = res.getInt(1);
                datos[1] = res.getString(2);
                datos[2] = res.getDouble(3);
                modelo.addRow(datos);
            }
            tblEntradas.setModel(modelo);
            new ColumnasTablas().tresColumnas(tblEntradas, 10, 100, 100);

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

}
