package Vista;

import Controlador.AbrirCajaControl;
import Controlador.ColumnasTablas;
import Controlador.Cronometro;
import Controlador.ManejadorFechas;
import Controlador.MyiReportVisor;
import Controlador.ProductoControl;
import Controlador.TablaRender;
import Controlador.VipNotaPedidoControl;
import Modelo.Conexion;
import Modelo.MySQLDAO.CajaDAO;
import Modelo.MySQLDAO.ConfiguracionDAO;
import Modelo.MySQLDAO.FlujoCajaDAO;
import Modelo.MySQLDAO.NotaPedidoDAO;
import Modelo.MySQLDAO.ProdPromocionDAO;
import Modelo.MySQLDAO.ProductoPresentacionDAO;
import Modelo.MySQLDAO.UsuarioDAO;

import Modelo.MySQLDAO.VentaNotaDAO;
import Modelo.NotaPedido;
import Modelo.ProdPromocion;
import Modelo.VentaNota;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author
 */
public class VipNotaPedido extends javax.swing.JFrame {

    DefaultTableModel modelo = null;
    MyiReportVisor mrv;
    HashMap parametros = new HashMap();
    double costoVIP;
    VipNotaPedidoControl vnp = null;

    public VipNotaPedido(String usuario) throws Exception {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
        vnp = new VipNotaPedidoControl(this);
        txtUsuario.setText(usuario);
        txtFecha.setText(new ManejadorFechas().getFechaActual());
        new Cronometro().iniciarCronometro(txtHora);
        txtCaja.setText(new AbrirCajaControl().getCajaDeUsuario(usuario));
        costoVIP = new ConfiguracionDAO().getPrecios(2);
        TablaRender ft = new TablaRender(153, 153, 255);//color de las celdas
        tblBox.setDefaultRenderer(Object.class, ft);//setea el color en la tabla
        LlenarTabla();
//        botones();
    }

    public VipNotaPedido() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formProductoEntradaVip = new javax.swing.JDialog();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtCaja = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnCobrar = new javax.swing.JButton();
        txtTotalCobrar = new javax.swing.JTextField();
        lblProducto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNumPersonas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBox = new javax.swing.JTable();

        formProductoEntradaVip.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton1.setText("PRODUCTO 3");
        formProductoEntradaVip.getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 230, 270));

        jToggleButton2.setText("PRODUCTO 1");
        formProductoEntradaVip.getContentPane().add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 230, 270));

        jToggleButton3.setText("PRODUCTO 2");
        formProductoEntradaVip.getContentPane().add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 230, 270));

        jToggleButton4.setText("PRODUCTO 4");
        formProductoEntradaVip.getContentPane().add(jToggleButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 230, 270));

        jToggleButton5.setText("PRODUCTO 4");
        formProductoEntradaVip.getContentPane().add(jToggleButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 230, 270));

        jToggleButton6.setText("PRODUCTO 5");
        formProductoEntradaVip.getContentPane().add(jToggleButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 230, 270));

        jButton1.setText("ACEPTAR");
        formProductoEntradaVip.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 660, 220, 50));

        jButton2.setText("CANCELAR");
        formProductoEntradaVip.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 660, 210, 50));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ENTRADAS VIP - BOX");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(0, 102, 153));
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("ENTRADAS");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 30));

        jLabel15.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("VIP - BOX");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, 30));

        jLabel18.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel18.setText("VIP - BOX");
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 20, -1, 30));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/receipt.png"))); // NOI18N
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 70));

        txtFecha.setEditable(false);
        txtFecha.setBackground(new java.awt.Color(0, 102, 153));
        txtFecha.setForeground(new java.awt.Color(255, 255, 255));
        txtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFecha.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "FECHA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1730, 20, 90, -1));

        txtHora.setEditable(false);
        txtHora.setBackground(new java.awt.Color(0, 102, 153));
        txtHora.setForeground(new java.awt.Color(255, 255, 255));
        txtHora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHora.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "HORA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(1640, 20, 90, -1));

        txtUsuario.setEditable(false);
        txtUsuario.setBackground(new java.awt.Color(0, 102, 153));
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "USUARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 20, 140, -1));

        jLabel17.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel17.setText("ENTRADAS");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 20, -1, 30));

        txtCaja.setEditable(false);
        txtCaja.setBackground(new java.awt.Color(0, 102, 153));
        txtCaja.setForeground(new java.awt.Color(255, 255, 255));
        txtCaja.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCaja.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "CAJA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.add(txtCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 140, -1));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 70));

        jPanel6.setBackground(new java.awt.Color(0, 102, 153));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 0, 0));
        jLabel19.setText("DISCOTECK");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, -1, -1));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel12.setText("DISCOTECK");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(942, 0, -1, -1));

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("MISTER JUERGA");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, -1, -1));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel11.setText("MISTER JUERGA");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(782, 0, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1010, 1920, 40));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn7.setBackground(new java.awt.Color(0, 153, 0));
        btn7.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn7.setForeground(new java.awt.Color(204, 255, 204));
        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iphone_7.png"))); // NOI18N
        btn7.setContentAreaFilled(false);
        btn7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn7.setFocusPainted(false);
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel2.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 210, 180));

        btn8.setBackground(new java.awt.Color(0, 153, 0));
        btn8.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn8.setForeground(new java.awt.Color(204, 255, 204));
        btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iphone_8.png"))); // NOI18N
        btn8.setContentAreaFilled(false);
        btn8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn8.setFocusPainted(false);
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel2.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 210, 180));

        btn9.setBackground(new java.awt.Color(0, 153, 0));
        btn9.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn9.setForeground(new java.awt.Color(204, 255, 204));
        btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iphone_9.png"))); // NOI18N
        btn9.setContentAreaFilled(false);
        btn9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn9.setFocusPainted(false);
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 210, 180));

        btn4.setBackground(new java.awt.Color(0, 153, 0));
        btn4.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iphone_4.png"))); // NOI18N
        btn4.setContentAreaFilled(false);
        btn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn4.setFocusPainted(false);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 210, 180));

        btn5.setBackground(new java.awt.Color(0, 153, 0));
        btn5.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 255, 255));
        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iphone_5.png"))); // NOI18N
        btn5.setContentAreaFilled(false);
        btn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn5.setFocusPainted(false);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel2.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 210, 180));

        btn6.setBackground(new java.awt.Color(0, 153, 0));
        btn6.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iphone_6.png"))); // NOI18N
        btn6.setContentAreaFilled(false);
        btn6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn6.setFocusPainted(false);
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel2.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 210, 180));

        btn1.setBackground(new java.awt.Color(0, 153, 0));
        btn1.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iphone_1.png"))); // NOI18N
        btn1.setContentAreaFilled(false);
        btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn1.setFocusPainted(false);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 210, 180));

        btn2.setBackground(new java.awt.Color(0, 153, 0));
        btn2.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iphone_2.png"))); // NOI18N
        btn2.setContentAreaFilled(false);
        btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn2.setFocusPainted(false);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 210, 180));

        btn3.setBackground(new java.awt.Color(0, 153, 0));
        btn3.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iphone_3.png"))); // NOI18N
        btn3.setContentAreaFilled(false);
        btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn3.setFocusPainted(false);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 210, 180));

        btn0.setBackground(new java.awt.Color(0, 153, 0));
        btn0.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btn0.setForeground(new java.awt.Color(255, 255, 255));
        btn0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iphone_0.png"))); // NOI18N
        btn0.setContentAreaFilled(false);
        btn0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn0.setFocusPainted(false);
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel2.add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 650, 210, 180));

        btnDel.setBackground(new java.awt.Color(255, 0, 0));
        btnDel.setFont(new java.awt.Font("SansSerif", 1, 90)); // NOI18N
        btnDel.setForeground(new java.awt.Color(255, 255, 255));
        btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/borrar.png"))); // NOI18N
        btnDel.setContentAreaFilled(false);
        btnDel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDel.setFocusPainted(false);
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        jPanel2.add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 210, 180));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 710, 940));

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCobrar.setBackground(new java.awt.Color(0, 102, 102));
        btnCobrar.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        btnCobrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCobrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cobrar.png"))); // NOI18N
        btnCobrar.setText("COBRAR");
        btnCobrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 820, 860, 100));

        txtTotalCobrar.setEditable(false);
        txtTotalCobrar.setBackground(new java.awt.Color(153, 153, 255));
        txtTotalCobrar.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 80)); // NOI18N
        txtTotalCobrar.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalCobrar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalCobrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txtTotalCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalCobrarActionPerformed(evt);
            }
        });
        jPanel3.add(txtTotalCobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 680, 360, 130));

        lblProducto.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lblProducto.setForeground(new java.awt.Color(255, 255, 255));
        lblProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProducto.setText("PRODUCTO...");
        lblProducto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel3.add(lblProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 620, 850, 50));

        jLabel1.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 70)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("S/.");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 710, 100, 90));

        txtNumPersonas.setEditable(false);
        txtNumPersonas.setBackground(new java.awt.Color(153, 153, 255));
        txtNumPersonas.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 100)); // NOI18N
        txtNumPersonas.setForeground(new java.awt.Color(255, 255, 255));
        txtNumPersonas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumPersonas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txtNumPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumPersonasActionPerformed(evt);
            }
        });
        jPanel3.add(txtNumPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 240, 150));

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CANTIDAD");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 240, 30));

        jLabel14.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 80)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("TOTAL");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 710, -1, -1));

        tblBox.setBackground(new java.awt.Color(153, 153, 255));
        tblBox.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 25)); // NOI18N
        tblBox.setForeground(new java.awt.Color(255, 255, 255));
        tblBox.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBox.setDragEnabled(true);
        tblBox.setFocusable(false);
        tblBox.setRowHeight(26);
        tblBox.setRowMargin(2);
        tblBox.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblBox.getTableHeader().setResizingAllowed(false);
        tblBox.getTableHeader().setReorderingAllowed(false);
        tblBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBoxMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBox);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 850, 600));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 1210, 940));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        String captura = txtNumPersonas.getText() + 7;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
        //txtCovers.setText("" + new ProductoControl().covers(2, numPersonas));
        //txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
        //int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
        lblProducto.setText("ENTRADA VIP");
        txtTotalCobrar.setText("" + new ProductoControl().total(cantPersonas, costoVIP));
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        String captura = txtNumPersonas.getText() + 8;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
        //txtCovers.setText("" + new ProductoControl().covers(2, numPersonas));
        //txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
        //int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
        lblProducto.setText("ENTRADA VIP");
        txtTotalCobrar.setText("" + new ProductoControl().total(cantPersonas, costoVIP));
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        String captura = txtNumPersonas.getText() + 9;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
//        txtCovers.setText("" + new ProductoControl().covers(2, numPersonas));
//        txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
//        int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
        lblProducto.setText("ENTRADA VIP");
        txtTotalCobrar.setText("" + new ProductoControl().total(cantPersonas, costoVIP));
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        String captura = txtNumPersonas.getText() + 4;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
//        txtCovers.setText("" + new ProductoControl().covers(2, numPersonas));
//        txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
//        int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
        lblProducto.setText("ENTRADA VIP");
        txtTotalCobrar.setText("" + new ProductoControl().total(cantPersonas, costoVIP));
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        String captura = txtNumPersonas.getText() + 5;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
//        txtCovers.setText("" + new ProductoControl().covers(2, numPersonas));
//        txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
//        int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
        lblProducto.setText("ENTRADA VIP");
        txtTotalCobrar.setText("" + new ProductoControl().total(cantPersonas, costoVIP));
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        String captura = txtNumPersonas.getText() + 6;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
//        txtCovers.setText("" + new ProductoControl().covers(2, numPersonas));
//        txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
//        int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
        lblProducto.setText("ENTRADA VIP");
        txtTotalCobrar.setText("" + new ProductoControl().total(cantPersonas, costoVIP));
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        String captura = txtNumPersonas.getText() + 1;
        txtNumPersonas.setText(captura);
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
        lblProducto.setText("ENTRADA VIP");
        txtTotalCobrar.setText("" + new ProductoControl().total(cantPersonas, costoVIP));

    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        String captura = txtNumPersonas.getText() + 2;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
//        txtCovers.setText("" + new ProductoControl().covers(2, numPersonas));
//        txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
//        int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
        lblProducto.setText("ENTRADA VIP");
        txtTotalCobrar.setText("" + new ProductoControl().total(cantPersonas, costoVIP));
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        String captura = txtNumPersonas.getText() + 3;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
//        txtCovers.setText("" + new ProductoControl().covers(2, numPersonas));
//        txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
//        int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
        lblProducto.setText("ENTRADA VIP");
        txtTotalCobrar.setText("" + new ProductoControl().total(cantPersonas, costoVIP));
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        String captura = txtNumPersonas.getText() + 0;
        txtNumPersonas.setText(captura);
        int numPersonas = Integer.parseInt(txtNumPersonas.getText());
//        txtCovers.setText("" + new ProductoControl().covers(2, numPersonas));
//        txtEntradas.setText("" + new ProductoControl().entradas(2, numPersonas));
//        int cantCovers = Integer.parseInt(txtCovers.getText());
        int cantPersonas = Integer.parseInt(txtNumPersonas.getText());
        lblProducto.setText("ENTRADA VIP");
        txtTotalCobrar.setText("" + new ProductoControl().total(cantPersonas, costoVIP));

    }//GEN-LAST:event_btn0ActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        tblBox.clearSelection();
        txtNumPersonas.setText("");
        txtTotalCobrar.setText("");
        lblProducto.setText("ENTRADA VIP");
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarActionPerformed
        try {
            int fila = tblBox.getSelectedRow();
            if (!txtNumPersonas.getText().trim().isEmpty()) {
                //REGISTRAR LA NOTA DE PEDIDO
                NotaPedido np = new NotaPedido();
                np.setFecha(new ManejadorFechas().getFechaActualMySQL());
                np.setHora(new ManejadorFechas().getHoraActual());
                np.setIdUsuario(new UsuarioDAO().getIdUsuario(txtUsuario.getText()));
                np.setIdcliente(1);
                np.setIdTipoComprobante(3);//nota de pedido
                np.setEstado(1);//activo
                np.setTipopago(1);//efectivo
                np.setnOperacion("0");//sin operacion
                np.setIdcaja(2);
                //System.out.println(v.getIdcaja());
                np.setIdFlujoCaja(new FlujoCajaDAO().getIdFlujo(new UsuarioDAO().getIdUsuario(txtUsuario.getText()), new CajaDAO().getIdCaja(txtCaja.getText())));
                System.out.println(new FlujoCajaDAO().getIdFlujo(new UsuarioDAO().getIdUsuario(txtUsuario.getText()), new CajaDAO().getIdCaja(txtCaja.getText())));
                //v.setIdFlujoCaja(2);

                NotaPedidoDAO npdao = new NotaPedidoDAO();
                if (npdao.registrar(np)) {
                    System.out.println("Nota de pedido registrada");
                }

                //segundo se registra la ventaNota
                VentaNota vn = new VentaNota();
                int ultimaNotaPedido = npdao.ultimaNotaPedido();
                System.out.println(ultimaNotaPedido);
                vn.setNumPersonas(Integer.parseInt(txtNumPersonas.getText()));
                vn.setNumCovers(Integer.parseInt(txtNumPersonas.getText()));
                vn.setTotal(Double.parseDouble(txtTotalCobrar.getText()));
                if (fila >= 0) {
                    vn.setTipoEntrada("BOX");
                    ProdPromocion pp = new ProdPromocionDAO().obtener(Integer.parseInt(tblBox.getValueAt(fila, 0).toString()), 2);
                    vn.setIdProdPromocion(pp.getIdProdPromocion());
                } else {
                    vn.setTipoEntrada("ENTRADA VIP");
                    //vn.setIdProdPromocion(//); MODAL PARA ELEGIR PRODUCTO DE ENTRADA VIP
                }

                vn.setIdNotaPedido(ultimaNotaPedido);

                VentaNotaDAO vndao = new VentaNotaDAO();
                if (vndao.registrar(vn)) {
                    System.out.println("ingreso al if");
                    //RESTAR STOCK
                    restarStock(vn.getNumCovers());

//                JOptionPane.showMessageDialog(rootPane, "VENTA REGISTRADA");
                    if (fila >= 0) {
                        //box
                        parametros.put("producto", lblProducto.getText());
                        parametros.put("personas", Integer.parseInt(txtNumPersonas.getText()));
                        parametros.put("total", Double.parseDouble(txtTotalCobrar.getText()));
                        parametros.put("nom_cajero", txtUsuario.getText());
                        parametros.put("idventa", ultimaNotaPedido);
                        mrv = new MyiReportVisor(System.getProperty("user.dir") + "\\reportes\\NotaEntradaBOX.jrxml", parametros, getPageSize());
                        mrv.setNombreArchivo("NotaBOX");
                        //mrv.exportarADocxConCopia("Notabox.docx");
                        try {
                            mrv.exportarAPdfConCopia();
                        } catch (Exception e) {
                            System.out.println(e.getMessage());
                        }

                    } else {
                        //entrada vip
                        parametros.put("personas", Integer.parseInt(txtNumPersonas.getText()));
                        parametros.put("nom_cajero", txtUsuario.getText());
                        parametros.put("idventa", ultimaNotaPedido);
                        mrv = new MyiReportVisor(System.getProperty("user.dir") + "\\reportes\\NotaEntradaVip.jrxml", parametros, getPageSize());
                        mrv.setNombreArchivo("NotaVIP");
                        //mrv.exportarADocxConCopia("Notavip.docx");
                        try {
                            mrv.exportarAPdfConCopia();
                        } catch (Exception e) {
                            System.out.println(e.getMessage());
                        }
                    }
//                    desseleccionarBotones();
                    btnDel.doClick();

                    LlenarTabla();
                }
            } else {
                JOptionPane.showMessageDialog(getRootPane(), "INGRESE NUMERO DE PERSONAS");
            }

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnCobrarActionPerformed

    private void txtNumPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumPersonasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumPersonasActionPerformed

    private void txtTotalCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalCobrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalCobrarActionPerformed

    private void tblBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBoxMouseClicked
        int fila = tblBox.getSelectedRow();
        lblProducto.setText(tblBox.getValueAt(fila, 1).toString());
        txtTotalCobrar.setText(tblBox.getValueAt(fila, 2).toString());
    }//GEN-LAST:event_tblBoxMouseClicked
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VipNotaPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn0;
    public javax.swing.JButton btn1;
    public javax.swing.JButton btn2;
    public javax.swing.JButton btn3;
    public javax.swing.JButton btn4;
    public javax.swing.JButton btn5;
    public javax.swing.JButton btn6;
    public javax.swing.JButton btn7;
    public javax.swing.JButton btn8;
    public javax.swing.JButton btn9;
    public javax.swing.JButton btnCobrar;
    public javax.swing.JButton btnDel;
    private javax.swing.JDialog formProductoEntradaVip;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    public javax.swing.JLabel lblProducto;
    public javax.swing.JTable tblBox;
    private javax.swing.JTextField txtCaja;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    public javax.swing.JTextField txtNumPersonas;
    public javax.swing.JTextField txtTotalCobrar;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void titulos() {
        String titulos[] = {"COD", "PRODUCTO", "PRECIO", "STOCK"};
        modelo = new DefaultTableModel(null, titulos);
        tblBox.setModel(modelo);
    }

    private void LlenarTabla() throws Exception {
        titulos();
        LimpiarTabla(tblBox, modelo);
        Conexion con = new Conexion();
        try {
            con.conectar();
            String sql = "SELECT prodpromocion.idproductopresentacion, producto.nombre, prodpromocion.precio1, productopresentacion.stock2\n"
                    + "FROM prodpromocion\n"
                    + "inner join productopresentacion on prodpromocion.idproductopresentacion = productopresentacion.idproductopresentacion\n"
                    + "inner join producto on productopresentacion.idproducto = producto.idproducto";
            PreparedStatement pst = con.getConexion().prepareStatement(sql);

            ResultSet res = pst.executeQuery();

            Object datos[] = new Object[4];

            while (res.next()) {
                datos[0] = res.getInt(1);
                datos[1] = res.getString(2);
                //crear condicional de la hora para modificar el precio(precio1->precio2) despues de las 12:00 de la noche            
                datos[2] = res.getDouble(3);
                datos[3] = res.getDouble(4);

                modelo.addRow(datos);
            }

            tblBox.setModel(modelo);

            pst.close();
            res.close();

            new ColumnasTablas().cuatroColumnas(tblBox, 50, 500, 100, 100);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            con.cerrar();
        }

    }

    public boolean restarStock(double quantity) throws Exception {
        try {
            int fila = tblBox.getSelectedRow();
            int id = Integer.parseInt(tblBox.getValueAt(fila, 0).toString());
            System.out.println("id: " + id);
            ProductoPresentacionDAO pdao = new ProductoPresentacionDAO();
            double stock = pdao.getStockProductoPresentacion(id, 2) - quantity;//-------
            System.out.println(stock);
            pdao.modificar(id, stock, 2);//tercer parametro 1 => ventas reales ; 2=>nota de pedido

        } catch (Exception e) {
            throw e;
        }
        return false;
    }

    private void LimpiarTabla(JTable tabla, DefaultTableModel model) {
        for (int i = 0; i < tabla.getRowCount(); i++) {
            model.removeRow(i);
            i -= 1;
        }
    }

    private int getPageSize() {
        int filas = 1;
        System.out.println("cantidad de filas: " + filas);
        int rowCount = 1;//FILAS DE GRACIA
        int fontSize = 7;//TAMAÑO DE LETRA DEL DETAIL
        int rowSize = fontSize + 2;//TAMAÑO DE LA FILA
        int caracteresPorLinea = 16;// CANTIDAD DE CARACTERES PARA QUE PASE A LA SIGTE LINEA
        for (int i = 0; i < filas; i++) {
            //String descripcionDeProducto = tbl_venta.getValueAt(i, 1).toString();
            rowCount += 1;//(1 + (int) (descripcionDeProducto.length() / caracteresPorLinea));
        }
        int cabecera = 80;
        int piePagina = 190;
//        int pageSize = (rowCount * rowSize) + cabecera + piePagina;
        int pageSize = (rowCount) + cabecera + piePagina;
        System.out.println("Cantidad de Filas finale:" + rowCount);
        System.out.println("pageSize:" + pageSize);
        return pageSize;
    }

}
